### ISSUE TITLE
Some shipped code packages do not have mandatory package-n4js.marker

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#1010]
Some shipped code packages do not have the mandatory `package.n4js-marker`file. For example the shipped code library `n4js-runtime-html5` is missing the mandatory n4js marker file (cf. https://github.com/eclipse/n4js/tree/master/n4js-libs/packages/n4js-runtime-html5). As a consequence, this library is not accessible as shipped code as it will not be considered an N4JS project when scanning the shipped code location as external library workspace.

**Comment by mor-n4** [comment]
Closing this as duplicate of #1027.
