### ISSUE TITLE
As a user I want the Library Manager to support GitHub version requirements

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1011]
Currently the library manager does not support dependencies using GitHub version requirements. This user story is about removing a work-around that was added (search for `GH-1011` in `NpmCLI.java`) and implementing proper support for this kind of version requirement.

### Background

A GitHub version requirement is a version requirement that points to a repository on github.com. For example, the following `package.json` defines a dependency to JSONSelect using a GitHub version requirement:
```
{
	"name": "Test",
	"version": "0.0.1",
	"devDependencies": {
		"JSONSelect": "dbo/JSONSelect",
		"express": "*"
	},
	"n4js": {
		"projectType": "library",
		"vendorId": "org.eclipse.n4js",
		"sources": {
			"source": [
				"src"
			]
		},
		"output": "src-gen"
	}
}
```
Another example would be a dependency such as
```
	"devDependencies": {
		"grunt-contrib-concat": "jacksonrayhamilton/grunt-contrib-concat"
	}
```

### Problem

In principle, the current implementation of the library manager should support GitHub version requirements. However, because the library manager installs dependencies one-by-one with individual invocations of npm (which is an issue in and of itself), it is running into the following, unexpected behavior of npm install:

1. create an empty folder on disk (in console; outside N4JS ide),
2. cd to this folder,
3. run `npm init` (accept defaults)
4. run `npm install JSONSelect@dbo/JSONSelect` --> this will install JSONSelect from @dbo's fork (as expected),
5. run `npm install express` --> this will install express and its dependencies BUT will remove JSONSelect

(tested with npm version 5.6.0)

With this behavior of `npm install`, the library runs into problems in case it encounters the dependency to JSONSelect before the one to express. Note that if the first call is `npm install JSONSelect@0.4.0` or something similar, the second call of npm install won't remove JSONSelect.

To reproduce the original problem in the library manager, remove the work-around in `NpmCLI.java` (search for `GH-1011`), create an N4JS project with the package.json shown above, and run the "Install missing dependencies" button (a NullPointerException should occur).

### ACs

1. Clarify the background of the above behavior of `npm install` (how do newer versions of npm behave? how does yarn behave?).
2. Adapt the library manager to cope with GitHub version requirements.
3. Remove the work-around that was added to the library manager with commit 236f1504b5e27884251534738c3576a2be10a657.
4. Add tests, etc.

**Comment by mor-n4** [comment]
Note that it is already planned to change the library manager to invoke `npm install` / `yarn install` only once. This might help solve this issue.

But: maybe we need this issue (i.e. support for GitHub version requirements) sooner than we are able to improve the library manager.

**Comment by mor-n4** [comment]
Seems to be related to the following npm issue: `https://github.com/npm/npm/issues/17379`
Fixed as of npm version 5.7.1

**Comment by mmews-n4** [comment]
@mor-n4 Looks like that this can be closed, right?

**Comment by mmews-n4** [comment]
(closed after short discussion)
