### ISSUE TITLE
As a user I want "Install missing dependencies" to properly handle cases of multiple version requirements for same npm package

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1017]
The "Install missing dependencies" button does not properly handle cases of multiple version requirements for the same npm package. Currently, it always uses the first version encountered.

To reproduce:
In an empty workspace, create two n4js projects. Add a dependency to `lodash` to both projects and use version requirement `>=4.17.2 <=4.17.10` in the first project and `>=4.17.0 <=4.17.3` in the second.

Problem: the "Install missing dependency" implementation will encounter `>=4.17.2 <=4.17.10` first and use that version, this will install lodash in 4.17.10 which violates the version requirement in the second project. (note: if the other version requirement were encountered first, then 4.17.3 would be installed which satisfies both version requirements)

Probably the best starting point for investigation is method `DependenciesCollectingUtil.resolve(String, String)`.

AC:
1. The "Install missing dependencies" button should properly handle the above case and similar cases.
2. Resolve the TODO in method `DependenciesCollectingUtil.resolve(String, String)` (search for `GH-1017`)

**Comment by mmews-n4** [comment]
npm support completely done by npm/yarn.
