### ISSUE TITLE
As a Build Smith, I need a 'www' subdirectory in n4js/docs folder

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#103]
This subdirectory needs a Jenkinsfile with build logic necessary for the Eclipse project HTML pages.

Additionally, investigate if Maven build can run an AsciiSpec docker image to generate the N4JS Language Spec alongside the Eclipse Help. If this can be easily implemented, this can be included with this task.

**Comment by mmews-n4** [comment]
merged here: https://github.com/eclipse/n4js/pull/121
