### ISSUE TITLE
Content assist on built-in classes wrongly lists all types mixed with expected members. 

### ISSUE THREAD

**Issue by torstenkraemer** [eclipse/n4js#1103]
In an Editor activating content assist for an Array type member access, it wrongly proposes type names mixed with real members:
```
let a: Array<string> = new Array<string>();
a.p
``` 
![screen shot 2018-08-31 at 18 39 23](https://user-images.githubusercontent.com/7485988/44925010-5b42ed80-ad4d-11e8-8522-9f078753c760.png)

**Comment by mor-n4** [comment]
now part of #1204. Closing this as duplicate.
