### ISSUE TITLE
Index synchronizer does not support shadowing from user workspace to external node_modules workspace

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1112]
reproduce:
* open IDE
* create project and 'n4js-node'
* use library manager and install 'n4js-node' in version 0.10.0-alpha.20180904.c7ef75ae
* press F5
* see error 'IndexOutOfSync'

**Comment by mor-n4** [comment]
When fixing this, remove the temporary work-around in the n4ideintegration test repository, commit `d125eafe0408c47ceb129bee3ca1847db1c43ea9`.

**Comment by mmews-n4** [comment]
@mor-n4 I cannot find the commit. Could you merge that?

Closing this as it is fixed.
