### ISSUE TITLE
As a smith I want to restructure the integration tests of N4JS

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1119]
For restructuring several N4JS IDE integration tests we need some minor adjustments and refactorings in utility methods used mainly by tests, plus and update of the `node` and `yarn` version used during builds.

**Comment by mor-n4** [comment]
Note: since the integration tests are using internal code bases as test data, the only changes that will appear in this public repository for this user story are the adaptations of the utility methods.
