### ISSUE TITLE
Remove code indirectly copied from Java

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1120]
Unfortunately Xtext contained some code copied from Java, which caused an IP problem:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=539108

Since we copied this code from Xtext, we also need to remove the affected code. Actually the Xtext IP issue was found when the N4JS code was checked, see bug report above.
There are some pull requests in the Xtext project which may help us:

https://github.com/eclipse/xtext-core/pull/870
https://github.com/eclipse/xtext-core/pull/871
https://github.com/eclipse/xtext-core/pull/872

I did a quick search (file search for "Mostly copied from") and found the following files which may need to be changed in the N4JS code

AbstractN4JSStringValueConverter.java (2 matches)
IdentifierValueConverter.java (2 matches)
N4JSStringValueConverter.java (2 matches)
RegExLiteralConverter.java
ExtensibleWizardNewProjectCreationPage.java

h2. Acceptance Criteria

- [x] Review these locations
- [x] look at the Xtext problems, try to identify more locations
- [x] fix them (maybe by using Sebastians PRs linked above).
- [x] When this issues is fixed, please report that as a comment in the CQ13482 (N4JS Initial Contribution): https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13482

**Comment by mor-n4** [comment]
`ExtensibleWizardNewProjectCreationPage.java` is based on Eclipse code (i.e. `org.eclipse.ui.dialogs.WizardNewProjectCreationPage`) so it is unrelated to the other cases and should be fine.

**Comment by mor-n4** [comment]
for a summary, see:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13482#c26
