### ISSUE TITLE
Jump to definition and searching for inherited fields does not work in external libraries

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#1122]
When we are inside a text editor displaying an N4JS file of an external library, jump to definition does not work. Moreover, when we search for inherited fields via Ctrl + 0, the inherited fields are not displayed. The outline view does not display inherited fields either.

This severely affects the usability of the IDE especially when working in a large codebase with huge external dependencies.

@yoosiba's comment: Suspicion: Navigation does not work to declarations for which only type information is there (and no N4JS code). These items are also not shown in the outline view for the same reason.

**Comment by qtran-n4** [comment]
@yoosiba You can also add a 👍  :D

**Comment by yoosiba** [comment]
enough emojis for my taste
