### ISSUE TITLE
Return type is not evaluated when calling the map function on immutable list (ImmutableJS)

### ISSUE THREAD

**Issue by aschaefer-n4** [eclipse/n4js#1143]
![image](https://user-images.githubusercontent.com/24318311/46352501-3dbdb800-c65a-11e8-9498-845184be1fdb.png)

the signature of the map function is:

`public <ThisT extends ImmutableIterable<K,M>, M>map(mapper: {function (value: V, key: K=, iter: this=): M},context: any=): ThisT;`

**Comment by mor-n4** [comment]
The signature of `List#map()` as defined in the definition file for immutable-js is contributing to this issue (compare with signature of Array#map()) and could be adjusted. But it has to be investigated if the type system should be changed to show the same behavior for both styles of signatures.

Self-contained example:
```javascript
class A {
	item: B;
}
class B {}

function foo(): string {
	// works as expected:
	// XPECT errors --> "Array<U> is not a subtype of string." at "new Array<A>().map(a => a.item)"
	return new Array<A>().map(a => a.item);
}
function foo1(): string {
	// surprising behavior (i.e. no error at the moment):
	// XPECT FIXME errors --> "Iterable<M> is not a subtype of string." at "new Array<A>().map(a => a.item)"
	return new List<A>().map(a => a.item);
}
function foo2(): string {
	// works as expected:
	// XPECT errors --> "Iterable<M> is not a subtype of string." at "new List<A>().map2(a => a.item)"
	return new List<A>().map2(a => a.item);
}


class List<T> {
	// signature of #map() as defined in immutable.n4jsd for List#map() (simplified):
	public <ThisT extends Iterable<M>, M>map(mapper: {function (value: T): M},context: any=): ThisT {
		return null;
	}
	// similar signature that leads to expected behavior on client side:
	public <M>map2(mapper: {function (value: T): M},context: any=): Iterable<M> {
		return null;
	}
}
```

**Comment by mor-n4** [comment]
The current behavior of the N4JS type system can be (partially) reproduced in Java (tested with the Eclipse Java compiler, version 4.7.3a, build ID 20180405-1200):
```java
class TestJava {

	static class A {}
	static final class A_final {}

	static interface I {}

	public static String sample2a() {
		return mapI(); // no error
	}
	public static A sample2b() {
		return mapI(); // no error
	}
	public static A_final sample2c() {
		return mapI(); // no error!!! (even though A_final does not itself implement I and is final, i.e.  we have an empty intersection)
	}

	public static <T extends I> T mapI() {
		return null;
	}
}
```

**Comment by mor-n4** [comment]
After looking into this some more:

This is an instance of the known topic of "empty intersections", for which we have ticket IDE-2302. For a more detailed explanation, see my earlier comment at https://github.com/NumberFour/n4js/issues/273#issuecomment-249779574.

I have added the above example as a comment to IDE-2302 and I'm closing this now as duplicate.
