### ISSUE TITLE
As a smith I want to document caching and partially completed tasks

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1153]
Write some documentation on the following topics:
* general overview of caching approaches and cases of caching in IDE (in design document; please also add 1-3 lines to "Tips and Tricks" chapter with pointers),
* current status of #926 (in task or in Google doc)
* ...

**Comment by mmews-n4** [comment]
See documentation in
* PR in extended repo
* comment https://github.com/eclipse/n4js/issues/926#issuecomment-431016001
