### ISSUE TITLE
Search in help / N4jsSpec sloppy 

### ISSUE THREAD

**Issue by torstenkraemer** [eclipse/n4js#1233]
Opening the help of the current IDE starts a web-page with search functionality.
Entering the term `covariant constructor`into the search box produces results but they are not in a usable shape. 
Cf. attached picture:
![screenshot 2019-01-31 at 09 12 02](https://user-images.githubusercontent.com/7485988/52041012-794d8d80-2539-11e9-963b-6f9a507f33c1.png)
* a - We get 3 times the same search-result -- but actually they point to different places
* a/b - A search result entry is *not pointing* to the correct sub-chapter but only to the root-node of the documentation - Despite, the link behind the result entry opens an actual occurrence of on of the search words.
* b - The context text is wrong (only showing) the document title
* c - The subchapter dedicated to `covariant constructors` - _5.2.5.4. Covariant Constructors_ (which is located at `http://127.0.0.1:59484/help/topic/org.eclipse.n4js.doc/dist/eclipse-html/N4JSSpec/classifiers.html?cp=5_4_1_4_3#_covariant-constructors` ) is ***missing from the search results***

**Comment by qtran-n4** [comment]
I will close this issue since it is Eclipse's issue.

**Comment by torstenkraemer** [comment]
@qtran-n4 would you please share the insights/reasoning of:

> since it is Eclipse's issue.

Any API documentation ?
Any explanation in the wiki ? 
Any related bugzilla-entries ?

Thank you.
