### ISSUE TITLE
Discovery: As a user I want to use ECMAScript imports (with ESM, webpack)

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1256]
We want to use ECMAScript import statements instead of System.js so that we can get rid of the special babel plugin handling our imports in the browser since webpack can not handle our special stuff.

We first need to know if the import statements with the semantic implicitly defined by ESM and webpack would work in all our cases. This is particularly true for dependencies cycles.

In order to test that, we want to implement a prototype of the transpiler which can be activated with a property in the package.json.

Related projects and webpages:
- https://github.com/tc39/proposal-dynamic-import/#import
- http://www.ecma-international.org/ecma-262/#sec-imports
- http://www.ecma-international.org/ecma-262/#sec-exports
- https://github.com/standard-things/esm

### Transpiler/IDE changes

- [x] add a flag in package.json to change transpiler behavior
- [x] remove imports used only for types (current behavior)
- [x] make imports specifiers fully qualified
- [x] remove special prefixes for node libraries (@@cjs, @@node)
- [x] revise import statement semantics
- [x] do not rewrite export statements

We will postpone support for  dynamic import syntax (also supported by ESM) (https://github.com/tc39/proposal-dynamic-import/#import). Also we will not write any tests except maybe some transpiler output tests.

### Runtime changes

- [ ] add nimport() to runtime library with ESM compatible to dynamic import proposal, i.e. implement nimport() (compiler won't accept import as function name!)
- [ ] add dynamic import functionality for mangelhaft with nimport

### Goal of Prototype

- [x] mangelhaft tests of some larger projects are running
- [x] run webpack on larger n4js based web project
- [x] manual test of larger n4js based project in browser

## Write Follow Up

Write a follow up user story for final version, taking findings of this user story into account. 

- The final version needs to support import() syntax
- We need clarify how to make esm available
- We need support esm with runners/testers

**Comment by mor-n4** [comment]
Status: the a prototype was implemented and tested with 2 major projects (stdlib, opr) and it seems to work fine (including tests).
However, nothing was merged to master as this is purely intended as a discovery task.
