### ISSUE TITLE
As a user I want array syntax similar to Typescript

### ISSUE THREAD

**Issue by dbo** [eclipse/n4js#1299]
N4JS and TypeScript have slightly different syntax for similar semantics. This issue shows an example of such a difference.

N4JS supports the following syntax for arrays: `[string]` equivalent to `Array<string>`
whereas typescript uses `string[]`.

What's even worse about this is that it has similarities with typescript's tuple syntax: `[string, number]` is equivalent to N4JS' `Iterable2<string, number>`.

**Comment by jpilgrim** [comment]
Note: [xxx] is the syntax for tuples in TypeScript
