### ISSUE TITLE
Try to clean up MANIFEST.MF files regarding the bundle version tag

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1305]
Some MANIFEST.MF files contain required bundles that reference a bundle version constraint. Since seems obsolete since we specify versions in the N4JS.setup file. Hence, we should try to remove those constraints since they are irritating and maybe even could cause problems when conflicting.

**Comment by torstenkraemer** [comment]
Version constraint in manifest files are used by Oomph to `compute` the target platform. As far as I remember without those constraints the computation is clueless. Restriction in the N4JS.setup file is more a performance optimization. 
In the end the consuming part should state what it will need and that would be the bundle here ...

**Comment by mmews-n4** [comment]
OK, I see. Thanks for the insights!

**Comment by mmews-n4** [comment]
Conflicts between the version tags of required bundle are apparently not shown, neither cause trouble (yet?): Currently, there are several conflicting constraints on dependencies, which are installed from the Eclipse Orbit or other locations. See picture below for `org.apache.commons`, installed from Orbit, which has version constraint as shown, but additionally constraints like `[1.2, 2.0)`.

![Uploading Screenshot 2019-05-03 at 15.09.37.png…]()

Usually, the Orbit provides only a very limited set of versions. 

Dependencies to Eclipse (esp. to xtext, xtend, xpect) are constrained by the repository locations in the `N4JS.setup` (resp. the targetplatform) file and hence, further constraints in the MANIFEST.MF are usually forgotten when updating those dependencies and lead to conflict situations.
