### ISSUE TITLE
As a developer I want to have access to the propery 'name' of functions

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1312]
Add a getter to provide access to the name of a function. Proposed solution below.

```js
@@Global @@ProvidedByRuntime

@Polyfill export external public class Function extends Function {
    public get name(): string;
}
```

**Comment by dbo** [comment]
Requires the builtin `Function` to be non-final.

**Comment by mor-n4** [comment]
See also:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

**Comment by mor-n4** [comment]
> Requires the builtin `Function` to be non-final.

As an alternative, we should consider allowing polyfills for final classes in general. Polyfilling is different from sub-classing (just using a similar syntax).

**Comment by mor-n4** [comment]
After looking into this a bit:

Polyfilling final classes had already worked for runtime polyfills. For static polyfills it did not work yet and I have fixed that on this branch. Also I added tests for both static and runtime polyfills of final classes.
