### ISSUE TITLE
As a smith I want to fully align scoping to npm/yarn

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1314]
BACKGROUND: _Most of the alignment of N4JS to npm/yarn has been completed in 2018 / early 2019 (`package.json` instead of `Manifest.MF`, redesign of library manager, simplification of runners, etc.). However, one final step remains in order to achieve full alignment:_

Currently, the N4JS IDE has the notion of a single set of external dependencies for the entire Eclipse workspace. This is in conflict with node/npm semantics in the following cases:

1. Given there are two projects P1 and P2 where each of them has a `node_modules` folder NM1 and NM2. Further given that both of the `node_modules` folders an npm is installed that has the same name, e.g. 'lodash'. At the moment, the type index of N4JS can contain only one package of the same name at once. Hence, 'lodash' of NM2 will shadow 'lodash' of NM1 (shadowing is resolved alphabetically). According to npm/node, however, each project can have its own dependencies without being affected by the other project's dependencies in any way.
2. The "side-by-side use case" (i.e. when having two projects P1, P2 in the Eclipse workspace with dependencies between each other) is no longer supported, but some remnants of the old behavior are still in the scoping and some other areas. However, P1 should be entirely invisible to P2, and vice versa.

In this user story, scoping and shadowing in the library manager (and other areas of the implementation such as validation, if need be) should be adjusted to ensure everything is handled in N4JS exactly as in node/npm.

The above applies similarly to the headless builder, so that should be adjusted accordingly.

### ACs

1. adjust scoping, library manager, etc. to
   1. support separate `node_modules` folders of unrelated projects,
   2. entirely disable the "side-by-side use case", i.e. disallow dependencies from one project to another when *not* having a yarn workspace setup.
2. ensure all validation (and their error messages) still make sense + consider adding new validations (if required)
3. ensure proper tool support is available for all related use cases (e.g. adjust wizards or quick fixes, if necessary).
4. remove all remaining aspects of the support for the side-by-side case from the N4JS implementation and the tests.
5. adjust and/or write new tests.
6. update design document, specification. etc.

**Comment by mmews-n4** [comment]
note that this / current behaviour forbids to have multiple projects in the yarn workspace with the same name (e.g. in different `packages/*` folders or with the same name as the yarn workspace project itself. see #2143
