### ISSUE TITLE
Small problem in N4JS.setup

### ISSUE THREAD

**Issue by merks** [eclipse/n4js#1327]
The setup archiver always has this failure:

Mirroring https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo_16.png
FAILED to load https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo_16.png
  ERROR: org.eclipse.oomph.util.IOExceptionWithCause: File not found: https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo_16.png 0 0 0

I think you moved
https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo_16.png

to

https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo.png

so please change your setup to reference that new logo location.

**Comment by mor-n4** [comment]
Thanks! We'll have a look.

**Comment by mmews-n4** [comment]
done in https://github.com/eclipse/n4js/issues/1331

**Comment by merks** [comment]
It still looks wrong here:

https://github.com/eclipse/n4js/blob/master/releng/org.eclipse.n4js.targetplatform/N4JS.setup#L21

**Comment by mmews-n4** [comment]
@merks You're right, my comment was unclear. I did not yet merge the branch of GH-1331.

**Comment by merks** [comment]
Thank you.  The setup archiver is now able to remove stale content from the zip file again, which it only do if it encounters no failures fetching any of the reachable resources.
