### ISSUE TITLE
As a smith I need the Oomph installer description to be updated

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1374]
As a smith I need the Oomph installer description to be updated. We still list Eclipse Oxygen in the readme and on the Eclipse download page.

- [x] update readme.md
- [x] update Eclipse N4JS project web page (download), maybe with screenshots and reference to the readme.md for details

**Comment by mor-n4** [comment]
FYI: I just pushed a minor update of the readme, see ea339d1.
