### ISSUE TITLE
Correctly handle scoping members of structural field initializer type ~i~C

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#140]
Currently, in case a `ParameterizedPropertyAccess` is bound to a member of the structural initializer type i.e. `~i~C`, no synthetic member is created (as opposed to composed member)
which is may be OK because the binding is unique. However, we receive `wrong write access` error messages. This example illustrates the issue:

```
class C {
	public set accWrite(v: int) { }
}
let ci: ~i~C;
// XPECT FIXME noerrors
ci.accWrite;
```

Also chains of structural field initializer types are not typed correctly.

```
class C {
	public set accWrite(v: int) {}
}

class G<T> {
	f: ~i~T;
}

let g: G<~i~C>;
// XPECT FIXME type of 'g.f' --> ~i~(~i~C)
g.f.accWrite;
```
## Acceptance Criteria
- The scoping of structural field initializer works correctly, also in the chaining case
- Consider if we may want to create a synthetic member in this case similar to the case with composed members. In the yes case, make sure the handling in both cases is based on the same mechanism.

**Comment by qtran-n4** [comment]
Related to: https://github.com/NumberFour/n4js/issues/12

**Comment by mor-n4** [comment]
It was decided to not create synthetic members in the above cases, for now. We will only reconsider this if we will run into problems with this approach.
