### ISSUE TITLE
Massive memory leakage in current IDE

### ISSUE THREAD

**Issue by dbo** [eclipse/n4js#1420]
The recent IDE versions show massive memory leaks while working. Over 1-2 hours memory usage grows to XX gigs. Going back it seems this might be related to the eclipse update, since the version from 201907192223 doesn't show it.

**Comment by dbo** [comment]
my leaks dump seems to match the one mentioned in https://bugs.eclipse.org/bugs/show_bug.cgi?id=549779

**Comment by mor-n4** [comment]
Updating to Eclipse 2019-09 solved the above memory issues.
