### ISSUE TITLE
As a user I do not want security issues in n4js-libs

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1430]
Github has detected some security issues in the n4js-libs dependencies.
We urgently need to fix these issues (for security and annoyance reasons).

These are the issues (https://github.com/eclipse/n4js/network/alerts):

- [x] eslint moderate severity -- n4js-libs/yarn.lock
- [x] diff high severity -- n4js-libs/yarn.lock
- [x] growl -- critical severity -- n4js-libs/yarn.lock
- [ ] eslint -- moderate severity -- n4js-libs/packages/n4js-cli/package.json

**Comment by mor-n4** [comment]
Thanks @dbo!
