### ISSUE TITLE
n4IDE is using eclipse icon instead of custom one on Windows

### ISSUE THREAD

**Issue by halitogunc** [eclipse/n4js#1437]
n4IDE uses eclipse icon as an app icon by default on Windows.

actual:
![image](https://user-images.githubusercontent.com/13641726/63702140-ac81a200-c826-11e9-87a9-735588c2b197.png)

expected:
![image](https://user-images.githubusercontent.com/13641726/63702158-b4414680-c826-11e9-96a3-52f4f814fcd4.png)

**Comment by mmews-n4** [comment]
Note that the following error output is not happening after fixing this issue: 
```
18:03:43  [IconExe] Error - 7 original icon(s) not replaced in /tmp/p2.brandingIron4469196830518184300/launcher.exe:
18:03:43  	- 48x48, 8 bits, 3752 byte(s) @ 121872
18:03:43  	- 32x32, 8 bits, 2216 byte(s) @ 125624
18:03:43  	- 16x16, 8 bits, 1384 byte(s) @ 127840
18:03:43  	- 48x48, 32 bits, 9640 byte(s) @ 129224
18:03:43  	- 32x32, 32 bits, 4264 byte(s) @ 138864
18:03:43  	- 16x16, 32 bits, 1128 byte(s) @ 143128
18:03:43  	- 256x256, 32 bits, 270376 byte(s) @ 144256
```
