### ISSUE TITLE
Default export is not working as expected

### ISSUE THREAD

**Issue by halitogunc** [eclipse/n4js#1442]
n4js is exposing all of the exported variables and is adding **"default"** key for the default exported one. 

Reproduce steps:
1. Create a file called **_constants.n4js_**
```typescript
export const NAMED_EXPORT_1 = "NAMED_EXPORT_1";
export const NAMED_EXPORT_2 = "NAMED_EXPORT_2";

export default public const DEFAULT_EXPORT = "DEFAULT_EXPORT"
```

2. Import the default 
``` typescript
import abc from "n4/constants";
console.log(abc);
```

- expected result:
```javascript
DEFAULT_EXPORT
```

- actual result:
```javascript
{
  NAMED_EXPORT_1: 'NAMED_EXPORT_1',
  NAMED_EXPORT_2: 'NAMED_EXPORT_2',
  default: 'DEFAULT_EXPORT' 
}
```

ps: Using the same name with default export variable does not have any effect while importing defaults.

see: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

**Comment by dbo** [comment]
I don't think there is a bug in the transpiled output, since import/export statements are not transpiled, but appear "as is" in the output. I think rather what you see is the CommonJS/esm handling of `esm` -- i.e. you require an esm module and get the module with all exports (including the reserved `default` export).

See https://github.com/standard-things/esm options. Using

```js
cjs: {
  dedefault: true
}
```

would do this.

**Comment by mor-n4** [comment]
True, I don't think this is a bug.

First, I do not know if the behavior of the old require() when importing from ES6 modules is even defined. At least, if I try to test this in node directly (without `-r esm`), I get an exception:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/mark-oliver.reiser/Desktop/test_js/other.mjs
```
(tested with node 10.13.0 and `--experimental-modules`).

Secondly, I think using require() for importing from an ES6 module (if it is even legal) doesn't correspond to a default import, which was a new feature in ES6, but rather to a namespace import. And when comparing it to that, the output shown in the task description is actually as expected. For example, with the two files
```
// file other.mjs
export const NAMED_EXPORT_1 = "NAMED_EXPORT_1";
export const NAMED_EXPORT_2 = "NAMED_EXPORT_2";

const DEFAULT_EXPORT = "DEFAULT_EXPORT";
export default DEFAULT_EXPORT;
```
and
```
// file test.mjs
import * as N from "./other.mjs"
console.log(N);
```
node will output
```
[Module] {
  NAMED_EXPORT_1: 'NAMED_EXPORT_1',
  NAMED_EXPORT_2: 'NAMED_EXPORT_2',
  default: 'DEFAULT_EXPORT' }
```
when invoked with
```
node --experimental-modules test.mjs
```
and this is pretty much the same as you get with the require().

**Comment by mmews-n4** [comment]
@dbo Can we close this?

**Comment by dbo** [comment]
yes
