### ISSUE TITLE
Eclipse-launched N4JS IDE crashes on large and fast text output

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#145]
When launching a N4JS IDE using an Developer Eclipse instance (e.g. via Run Configuration N4JS_IDE) on macOS, it is easy to cause a total crash of the IDE by executing the following N4JS file:

```
while(1) { console.log("Line"); }
```

The output of this script causes large and quick text output in the console which crashes the IDE.

I suspect the cause of this issue to be related to crashes the team has experiencing over the last few weeks, when deleting all of the editor content. 

The console output of such a crash looks like this:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fffdd983050, pid=3825, tid=0x0000000000000307
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libsystem_platform.dylib+0x2050]  _platform_memmove$VARIANT$Nehalem+0x70
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# (...)/Eclipse.app/Contents/MacOS/hs_err_pid3825.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

This happens only when launching the IDE out of an Developer Eclipse instance. This does not happen to downloaded binary versions of the IDE. For now this is only known to happen on macOS.

**Comment by mor-n4** [comment]
Some of these problems were fixed in Eclipse Oxygen, so we should try again after updating to Oxygen.

**Comment by yoosiba** [comment]
does not happen after update to Oxygen
