### ISSUE TITLE
n4jsRuntimeLink may not be a symbolic link on Windows

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#1489]
Even though I have run BuildN4jsLibs.mwe2 the Xpect output tests do not work. E.g. I get 119 failures in the n4js.spec.tests, that is all output tests.

The failure is caused in org.eclipse.n4js.test.helper.hlc.N4jsLibsAccess.assertN4jsLibsAreBuilt(Path):

```
 Assert.assertTrue("not a symbolic link pointing to package \"" + N4JSGlobals.N4JS_RUNTIME + "\": "
		+ n4jsRuntimeLink + warning, Files.isSymbolicLink(n4jsRuntimeLink));
```
fails:

```
java.lang.AssertionError: not a symbolic link pointing to package "n4js-runtime": N:\oomph\n4js-master\git\n4js\n4js-libs\node_modules\n4js-runtime
******************************************************************
Maybe you forgot to run MWE2 workflow BuildN4jsLibs?
******************************************************************
```
I added a new assertion and uncommented the assertion above as follows:

```
Assert.assertTrue("path package does not exist \"" + N4JSGlobals.N4JS_RUNTIME + "\": "
				+ n4jsRuntimeLink + warning, Files.exists(n4jsRuntimeLink));
```

Now my tests are all working!

The assertion was added with #1281 by @mor-n4... Could you give me a hint what is going on?

Some background about my set up: It is Windows 10 with n4js installed on an external drive. Since the drive may be mounted with different drive names, I use a `subst n: d:\` to have a fixed drive name (i.e. n:).

Do we actually need a symbolic link there? Because in my case, the folder is there, but it is not a symbolic link.

**Comment by mor-n4** [comment]
This symbolic link is created by yarn, so maybe yarn is working differently on Windows (creating copies instead of symbolic links). I'll have a look.

**Comment by jpilgrim** [comment]
Update: as a matter of fact, `\n4js\n4js-libs\node_modules\n4js-runtime `is a symbolic link:

```
 <JUNCTION>     n4js-runtime [N:\oomph\n4js-master\git\n4js\n4js-libs\packages\n4js-runtime]
```

It seems something is wrong with the `Files.isSymbolicLink` (or how we use it..):

```
try {
			Path real = n4jsRuntimeLink.toRealPath();
			System.out.println("Link path: " + n4jsRuntimeLink);
			System.out.println("Real path: " + real);
			System.out.println("Is symbolic link: " + Files.isSymbolicLink(n4jsRuntimeLink));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```
prints out:
```
Link path: N:\oomph\n4js-master\git\n4js\n4js-libs\node_modules\n4js-runtime
Real path: D:\oomph\n4js-master\git\n4js\n4js-libs\packages\n4js-runtime
Is symbolic link: false
```

Well... I have no idea about how Windows (and yarn under Windows) handels or creates links. I have to investigate.

**Comment by jpilgrim** [comment]
Another question, maybe @dbo can answer that:

I tried to manually run `yarn install` in the n4hs-libs folder (from command line on Window) and I got the following error:

```
yarn install v1.17.3
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
info If you think this is a bug, please open a bug report with the information provided in "N:\\test2\\n4js\\n4js-libs\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

In `.npmrc` I found the following lines:

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
//localhost:4873/:_authToken=${NPM_TOKEN}
//localhost:4874/:_authToken=${NPM_TOKEN}
``` 

After removing these lines I was able to successfully run `yarn install`.

@dbo Can we remove these lines from .npmrc in n4js-libs?

**Comment by mor-n4** [comment]
> prints out:
> 
> ```
> Link path: N:\oomph\n4js-master\git\n4js\n4js-libs\node_modules\n4js-runtime
> Real path: D:\oomph\n4js-master\git\n4js\n4js-libs\packages\n4js-runtime
> Is symbolic link: false
> ```

Maybe related to the difference between symbolic link and hard link.

If it is too much hassle, we can simply change the assertion to "exists" under Windows.

**Comment by mor-n4** [comment]
> ```
> yarn install v1.17.3
> error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
> info If you think this is a bug, please open a bug report with the information provided in "N:\\test2\\n4js\\n4js-libs\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```

I don't think this is specific to Windows, I saw this error under macOS / linux, too.

Make sure an environment variable `NPM_TOKEN` is set. As value you can use `dummy` as long as you do not want to publish anything to the official npm registry.

**Comment by dbo** [comment]
@jpilgrim You need the auth-line as part of the npmrc when publishing to npmjs.com. However, you could append these lines before publishing, so everybody else does not have the hassle of setting that env variable.
