### ISSUE TITLE
As a user I want support for optional chaining (aka elvis operator, etc.)

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1494]
There exists a Javascript proposal for null-safe/undef-safe property access, index access, and function invocation, called "optional chaining". This proposal is now in stage 3. Similarly, a closely related proposal for an "elvis operator" exists, called "nullish coalescing".

See:
https://github.com/tc39/proposal-optional-chaining
https://github.com/tc39/proposal-nullish-coalescing
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

There is also a Babel plugin available:
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

### ACs

1. implement syntax,
2. implement transpilation to ES5/6,
3. adjust type system and null/undef-analysis,
4. add tests,
5. adjust specification & documentation.

### Proposed transpilation

```
var foo = object.foo ?? "default";
```
should become
```
var _uniqueVarName;
var foo = (_uniqueVarName = object.foo) !== null && _uniqueVarName !== void 0 ? _uniqueVarName : "default";
```
---
```
a?.b.c
```
should become
```
var _uniqueVarName;

(_uniqueVarName = a) === null || _uniqueVarName === void 0 ? void 0 : _uniqueVarName.b.c;
```

**Comment by szarnekow** [comment]
Merged
