### ISSUE TITLE
Check handling of cancel indicator in type resolution

### ISSUE THREAD

**Issue by szarnekow** [eclipse/n4js#150]
Investigating #66 and some test problems (https://github.com/eclipse/n4js/blob/master/tests/org.eclipse.n4js.ui.tests/src/org/eclipse/n4js/dirtystate/CanLoadFromDescriptionPluginUITest.xtend#L275) @mor-n4  and I figured that there are inconsistencies how cancellation is propagated during type resolution.

Multiple things that need to be double checked:
- Is the cancel indicator properly propagated when resource boundaries are crossed during type resolution?
- Do we use OperationCanceledManager.checkCanceled(CancelIndicator) rather than isCancelled?
- Do we catch OperationCanceledError or OperationCanceledException by accident rather than OperationCanceledManager.propagateIfCancelException(Throwable)?
- Do we pass on the correct cancel indicator, e.g. in the editor context?

**Comment by mor-n4** [comment]
in particular:
* how to propagate the cancel indicator when starting a new type inference of same or different resource (adding cancel indicators to the rule environment might be a (partial) solution)
* how to make sure Xsemantics does not catch and digest `OperationCanceledException`s (or is this already taken care of by Xsemantics?)
