### ISSUE TITLE
XPECT uses self-referencing message

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#151]
```javascript
// XPECT warnings --> "Dispensable use of conditional expression. The expression 'true' always evaluates to true, so only the left-hand side will ever be evaluated." at "true"
true ? 1 : 0;
```

The test case in the code above always fails, since XPECT computes the following test expectation :

`// XPECT warnings --> "Dispensable use of conditional expression. The expression '// XPECT warnings --> "Dispensable use of conditional expression. The expression 'true' always evaluates to true, so only the left-hand side will ever be evaluated." at "true"\ntrue' always evaluates to true, so only the left-hand side will ever be evaluated." at "true"`

The expectation itself includes the comment and the string `XPECT` again, which creates a second test case... thus, this expectation cannot be used.

**Comment by lbeurerkellner** [comment]
Interestingly enough, this doesn't happen if you use an extra pair of parenthesis:

```
// XPECT warnings --> "Dispensable use of conditional expression. The expression 'true' always evaluates to true, so only the left-hand side will ever be evaluated." at "true"
(true ? 1 : 0);
```

This works just fine.

**Comment by mor-n4** [comment]
This is a bug in XPECT, not in N4JS.

Closing this as invalid.
