### ISSUE TITLE
N4JS IDE product built for macOS on Eclipse servers cannot be launched

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1512]
The macOS version of the N4JS IDE built on Eclipse's Jenkins can no longer be launched. The following error message is shown (even before the workspace selection dialog appears):
<img width="463" alt="image" src="https://user-images.githubusercontent.com/7124687/66894447-ae7b0c80-eff0-11e9-93a5-e361b1354568.png">

To reproduce:
1. download `n4jside-macosx.cocoa.x86_64.dmg` from
   https://download.eclipse.org/n4js/products/nightly/201910102301/
   (commit cbd64b797357c138b4dd8e9045b11a6fad861f20)
2. install and launch
3. the above error should show up.

The file `n4jside-macosx.cocoa.x86_64.zip` from the above download location is also producing an error, but with a different dialog/message:
![image](https://user-images.githubusercontent.com/7124687/67032594-2a21aa00-f114-11e9-90f5-66597aee6cba.png)

NOTE: I have tried to reproduce this with local maven builds, but this error does not occur when the product is being built locally (tested both with and without the `-DexcludeJRE` flag and in both cases the problem does not occur when built locally).

**Comment by AnonAuth** [comment]
I also encountered this issues. I can confirm that the following build still works: https://archive.eclipse.org/n4js/products/nightly/201907162301/

**Comment by lbeurerkellner** [comment]
I have also encountered this issues. I can confirm that the following build still works: https://archive.eclipse.org/n4js/products/nightly/201907162301/

**Comment by mmews-n4** [comment]
Linux version under Ubuntu works.

**Comment by mmews-n4** [comment]
On my machine I can start the macos version of the n4jsIDE after I made a trivial change (added new line) to the `info.plist` file within the Contents folder of the product. Reverting the change will again result in the error above.

@mor-n4  A note to opening the zip: It worked for me when right-clicking on the app and then chose _Open_ in the dialog. After that, the same issue regarding JNI_CreateJavaVM symbol appears.

**Comment by lbeurerkellner** [comment]
This is speculation, but since it works fine when build locally or after local modification, this could be a signing issues?

**Comment by mmews-n4** [comment]
@lbeurerkellner  💯 

Just tried to start it on the console and got the following message:

```
$ ./n4jsIDE.app/Contents/MacOS/n4js_ide 
2019-10-31 12:13:08.324 n4js_ide[67586:993016] Error loading /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/MacOS/libjli.dylib:  dlopen(/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/MacOS/libjli.dylib, 265): no suitable image found.  Did find:
	/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/MacOS/libjli.dylib: code signature in (/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/MacOS/libjli.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Comment by mor-n4** [comment]
This was caused by the update to Eclipse 2019-09.

As of this update, certain entitlements have to be specified when signing the product for macOS, which was missing.

The other problem with the zip archive producing a broken app-bundle was caused by incorrect/missing file mode information in the zip-archive created by the Eclipse signing service for macOS.

These two should be fixed by the above PR.

There is another open issue, that I won't fix as part of this ticket: as of macOS Catalina an additional step is required in addition to signing: notarization. Created #1762 for that.
