### ISSUE TITLE
Review resource set and index related API in IN4JSCore and its clients

### ISSUE THREAD

**Issue by szarnekow** [eclipse/n4js#1586]
With all the current changes in the LSP context, maybe now is a good time to reconsider these two methods in `IN4JSCore` in general. I think their intended use case is still valid, but maybe there's a better way to do it. Let's discuss this on Monday, also with @mmews-n4 (no need to postpone this PR, though).

_Originally posted by @mor-n4 in https://github.com/eclipse/n4js/pull/1584_

**Comment by mmews-n4** [comment]
Still valid and should be discussed, but IN4JSCore (and related) requires major clean-up in general. When performing this clean-up, this topic will be revised anyway.
