### ISSUE TITLE
Allow imported any+ namespaces to be used as functions

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1631]
Mind the example below:

```ts
import * as lib_decompress+ from "decompress";
// FIXME XPECT noerrors --> "Not a function or method: lib_decompress." at "lib_decompress"
lib_decompress();
```

**Comment by mor-n4** [comment]
After looking into this a bit: I think the namespace itself will never be a function (when using ES6 imports).

If there is a `plain.js` with either
```javascript
module.exports = ()=>console.log('hello from plain!');
```
or
```javascript
export default ()=>console.log('hello from plain!');
```
and another file `Main.n4js` with
```javascript
import * as P+ from "plain"
P();
```
will fail at runtime with `TypeError: P is not a function`. Instead, the code `P.default()` in the second line would work.

So what we actually want is probably a "dynamic default import", such as:
```javascript
import P+ from "plain" // not supported yet
P();
```
