### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eclipse/n4js#1640]
Hello Eclipse N4JS team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Eclipse N4JS project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by mmews-n4** [comment]
```html
<tr>
	<td><a href="https://www.eclipse.org/n4js/">N4JS</a></td>
	<td>N4JS is a general-purpose programming language based on ECMAScript with several additional features. In particular, N4JS adds a static type system as reliable as that of Java, but with the flexibility of JavaScript.</td>
	<td>EPL-1.0</td>
	<td>Language</td>
	<td>Eclipse N4JS Project, enfore AG</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you!

**Comment by miklossy** [comment]
The `N4JS` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by mmews-n4** [comment]
Thanks!
