### ISSUE TITLE
As a developer I need correct incremental building when using the N4JS LSP server

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1675]
The builder in the N4JS LSP server does not always correctly update issues when building incrementally. It seems this is caused by a different behavior of Xtext's LSP builder vs. Xtext's Eclipse builder (see comment below). In addition, the LSP command "N4JS: Rebuild" in VSCode does not always update all issues; it is not clear if this is related or a separate issue.

### To Reproduce - Method 1

Create a new N4JS project, install `n4js-runtime` and create the following files:
```javascript
// A.n4js
export public class A {
    public m() {}
}
```
```javascript
// B.n4js
import {A} from "A"
export public class B extends A {}
```
```javascript
// Main.n4js
import {B} from "B"
new B().m();
```
Now follow these steps:
1. open VSCode and open the root folder of the above N4JS project.
2. perform a build with action "N4JS: Rebuild" (via CMD+Shift+P).
3. open file "A.n4js" (this should be the only open file during the entire test).
4. comment-out the entire class `A` and save the file;
   -> correct errors will show up for files `B.n4js` and `Main.n4js` (but don't open those files!).
5. comment-in class A and save the file;
   -> the errors for file `B.n4js` will disappear, but not the error in file `Main.n4js`.
6. touch file A.n4js (i.e. add empty lines etc. and save);
   -> the error in file `Main.n4js` will still not disappear.
7. perform a build with action "N4JS: Rebuild" (via CMD+Shift+P);
   -> the error in file `Main.n4js` will still not disappear.
8. touch file A.n4js;
   -> now the error in file `Main.n4js` will disappear.

Instead of steps 7. and 8., files `B.n4js` and `Main.n4js` could be opened to make the error in `Main.n4js` go away.

### To Reproduce - Method 2

Create a new N4JS project, install `n4js-runtime` and create the following files:
```javascript
// A.n4js
export public var a: string;
```
```javascript
// B.n4js
import {a} from "A"
export public var b = a;
```
```javascript
// Main.n4js
import {b} from "B"
b.length;
```
1. open VSCode and open the root folder of the above N4JS project.
2. perform a build with action "N4JS: Rebuild" (via CMD+Shift+P).
3. open file "A.n4js" (this should be the only open file during the entire test).
4. change the type of variable a to `number` and save the file;
   -> the expected error will not show up in `Main.n4js` (but don't open the file!).
5. touch file A.n4js (i.e. add empty lines etc. and save);
   -> still the expected error will not show up.
6. perform a build with action "N4JS: Rebuild" (via CMD+Shift+P);
   -> now the expected error will show up.
7. change the type of variable a back to `string` and save the file;
   -> the now obsolete error in `Main.n4js` won't disappear.
8. perform a build with action "N4JS: Rebuild" (via CMD+Shift+P);
   -> obsolete error still does not disappear.
9. touch file A.n4js;
   -> obsolete error still does not disappear.
10. open file `Main.n4js`;
   -> obsolete error still does not disappear.
11. touch file `Main.n4js`;
   -> now the obsolete error disappears.

### ACs

1. Review the scenarios described above and try to find more problematic cases,
2. check LSP command "N4JS: Rebuild" to see if it is related, otherwise create a separate ticket,
3. investigate exact behavior of Xtext Eclipse builder (w.r.t. `#isAffected()`, etc.),
4. change Xtext LSP builder accordingly,
5. reconsider the N4JS implementation of `#isAffected()`,
6. reconsider the problems solved by `CanLoadFromDescriptionHelper` and check if there might be a better solution in the context of the changes applied during this story,
7. create an (at least initial) test suite for incremental build scenarios based on `AbstractIdeTest` (if it turns out to be too much, create follow-up task),
8. update/amend design document,
9. search entire N4JS code base for `TODO GH-1675` (some other tasks could not be completed without fixing this story).

_NOTE: this user story is only about correctness of incremental building. An older user story GH-591 (formerly https://github.com/NumberFour/n4js/issues/175) exists for changing `#isAffected()` or related code in order to improve performance (i.e. to rebuild as few modules during an incremental build as possible); the performance problems addressed in this older user story are not specific to the LSP builder but affect the Eclipse builder in the same way._

**Comment by mor-n4** [comment]
Some early findings:

There seem to be major differences how the LSP builder runs incremental builds, compared to the Eclipse builder. Given a set of changed resources, the Eclipse builder follows this approach:
1. rebuild changed resources,
2. ask other resources if they are affected (with `#isAffected()`) and rebuild those affected,
3. ask remaining other resources if they are now affected (with `#isAffected()`) and rebuild those affected,
4. ... and so on until all resources have been built OR none of the remaining are affected.

The LSP builder seems to use this approach:

1. ask other resources if they are affected,
2. rebuild changed and affected resource.
   END

So, the LSP builder does not poll `#isAffected()` iteratively AND it polls `#isAffected()` before building the changed resources (but not sure about the latter statement; has to be double-checked!).

Some related areas in the code are:
* the loop starting at https://github.com/eclipse/xtext-eclipse/blob/c443adcf2e3f17de15c748345c13d73971b78fce/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java#L193
   in particular the line https://github.com/eclipse/xtext-eclipse/blob/c443adcf2e3f17de15c748345c13d73971b78fce/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java#L300
* in N4JS we use a copy of an old version of that code: https://github.com/eclipse/n4js/blob/b12c83bd1c2c1902087f7ed4fc6c80df4d979546/plugins/org.eclipse.n4js.ui/src/org/eclipse/n4js/ui/building/N4ClusteringBuilderState.java#L222-L261
* the LSP variant of this seems to be the code around: https://github.com/eclipse/n4js/blob/b12c83bd1c2c1902087f7ed4fc6c80df4d979546/plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/XStatefulIncrementalBuilder.java#L106

Overall, this seems straightforward to fix, but this task is also about an overall review of the builder code and our `#isAffected()` implementation (plus test suite, etc.).

**Comment by mmews-n4** [comment]
The test suite should include the following user interaction with the LSP server and should concentrate on protocol and infrastructure features, but not on language features:
- open/close file
- change opened/closed file (to cause/solve an issue)
- save file

Regarding files, the tests should consider n4js files and package.json files, both in workspace projects and in node_modules projects.

Regarding the tested implementation the tests should validate that dirty/clean state is handled (transpilation only when in clean state), node_modules projects are treated differently (e.g. no validation/transpilation), and that the rebuilt action refers to workspace projects only.

Note that sometimes the desired test result is unclear at the moment. This could be specified in a follow-up user story. However, the test suite would make the current behaviour and changes visible.

**Comment by mor-n4** [comment]
For reference: implementation of `#isAffected()` and `CanLoadFromDescriptionHelper` was not investigated in great detail during this task, because
* problems described in task description were not related to N4JS-implementation of `#isAffected()` but to a difference in behavior of the Xtext LSP builder compared to the Xtext Eclipse builder,
* of the 3 public methods in `CanLoadFromDescriptionHelper` none was really relevant to the topic of this task:
   * `#mustLoadFromSource()` is deactivated entirely and has no effect, at the moment (see `#isLoadFromSourceDeactivated()`),
   * `#dependsOnAny()` seems to be used only in the Eclipse UI case (and this task is focused on the LSP builder),
   * `#createResource()` is a minor, unproblematic utility and not related to the topic of this task.

However, an overall review of `#isAffected()` and `CanLoadFromDescriptionHelper` will probably still be useful in the future.
