### ISSUE TITLE
As a developer I want to use organize imports in the N4JS VSCode extension

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1677]
Migrate the existing organize imports from the N4JS Eclipse IDE to the N4JS lsp server as a code action. Consider existing documentation about `CodeActionKind#SourceOrganizeImports` (https://microsoft.github.io/language-server-protocol/specification). Regarding a keyboard shortcut, either the current one could be used or the same that typescript uses. It should be considered to also migrate tests for this feature.

**Comment by mor-n4** [comment]
Note: in consistency with other language servers (in particular the one for typescript), we decided to make organize imports a strictly non-interactive operation in the LSP case (i.e. do not add missing imports if there are multiple possible elements that could be used for a given unresolved reference).

In addition, for consistency and performance reasons, organize imports will no longer add missing imports even if there is only a single possible element that could be used.

For adding missing imports, we have code completion (adding a single import) and quick fixes (adding many missing imports).
