### ISSUE TITLE
Regex grammar cannot parse '_'

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1686]
Reproduce with

```ts
// FIXME xpect nowarnings --> "mismatched input '_' expecting '/'" at "_"
let regex = /1_1/;
```

**Comment by mor-n4** [comment]
A related TODO from #1725:

> Make this test pass:
> (ParserTest.xtend in regex package)
> 
> ```
> 	@Test
> 	def void test_43() {
> 		'''/[_]/'''.assertValid
> 	}
> ```

**Comment by szarnekow** [comment]
Please bear in mind that #1725 was already merged via https://github.com/eclipse/n4js/pull/1726

**Comment by szarnekow** [comment]
Appears to be fixed.

**Comment by mmews-n4** [comment]
I just noticed that this specific error still exists. However, it is true that GH-1725 was fixed that the related test is working.
