### ISSUE TITLE
As a smith I want to improve reduced reflection feature to es6 classes

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1693]

**Comment by mor-n4** [comment]
It seems `origin` is not set in all elements, even though the property is declared in `N4Element` in file `builtin_n4.n4ts`. E.g.
```javascript
class C {
	m() {}
}
console.log(C.n4type.members()[0].origin); // prints "undefined"
```

**Comment by mor-n4** [comment]
Reflection has to omit some implicit members created by the transpiler. Make sure this is handled consistently for all such members (probably the tag `hiddenFromReflection` in class `InformationRegistry` should be used in all those cases).

**Comment by mor-n4** [comment]
I have rebased the contents of branch `GH-574B` onto the latest master. The result can be found on branch `GH-1693`. Branch `GH-574B` still exists, for reference.
