### ISSUE TITLE
LSP builder not using Xtext API for handling cancellation exceptions

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1749]
Some methods in the LSP builder catch `java.util.concurrent.CancellationException` but do not catch `org.eclipse.core.runtime.OperationCanceledException` which is thrown by our code, resulting in behavior for "unknown exception" to be executed in case of cancellation.

Probably the Xtext API for handling cancellation should be used instead, e.g. something like `operationCanceledManager.isOperationCanceledException(t)`.

This applies to methods:
```
org.eclipse.n4js.ide.xtext.server.XBuildManager.doIncrementalBuild(boolean, CancelIndicator)
org.eclipse.n4js.ide.xtext.server.build.XStatefulIncrementalBuilder.launch()
```
(check code for more cases).

Seems to be done properly in:
```
org.eclipse.n4js.ide.xtext.server.build.XIncrementalBuilder.build(XBuildRequest, IResourceClusteringPolicy)
```

**Comment by mor-n4** [comment]
For reference:

As it turned out while working on this, using _only_ the `OperationCanceledManager` is not possible in all places in bundle `org.eclipse.n4js.ide`, because `OperationCanceledManager` does not handle Java's `java.util.concurrent.CancellationException`. So, in places where that exception might occur, it must be handled explicitly, maybe in addition to using `OperationCanceledManager` for the other kinds of cancellations.

Alternatively, support for `java.util.concurrent.CancellationException` could be added to `OperationCanceledManager`, but this would require a change in Xtext (not done as part of this task).

**Comment by szarnekow** [comment]
cf https://github.com/eclipse/n4js/blob/master/plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/concurrent/XRequestManager.java#L125
