### ISSUE TITLE
As a developer I want the incremental LSP builder to update all projects affected by a workspace change

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1766]
This is a follow up to #1729.

In user story #1729 an infrastructure was created for detecting workspace changes (e.g. project added/removed) and for updating the internal data structures of the LSP builder (i.e. `N4JSWorkspaceConfig`, `N4JSProjectConfig`). Also newly added projects should be built properly after those additions.

When and how existing, unchanged projects are affected by such workspace changes was not yet investigated and implemented in detail yet. That is the goal of this user story.

For example, if a project P1 has defined a dependency to a project "P2" in its `package.json` but project P2 does not exist in the workspace yet, then also project P1 has to be rebuilt the moment a project called "P2" is being added to the workspace.

NOTE: test class `IncrementalBuilderWorkspaceChangesTest` already contains two test cases, search for `TODO GH-1766`.

**Comment by mmews-n4** [comment]
Also consider to respect changes in the node_modules folder and then update dependent projects accordingly (Otherwise, move this task to a separate user story.).
