### ISSUE TITLE
As a smith I want some information on the LSP server's health without a host Eclipse

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1795]
When observing a bug/oddity on a developer machine it should be possible to get some information about the state of the LSP server even without having a host Eclipse instance that runs the server in debug mode.

Of course it is impossible to provide enough information to find the cause of all bugs, but some hints would be helpful.

Output could go to VSCode's output view (like ordinary logging) or to a file. Output could be triggered manually or upon certain occasions.

Also Java's `jps`, `jstack` tools should be investigated. How helpful are they when used with the LSP server? The information available through those need not be provided by us.

**Comment by mmews-n4** [comment]
Notes from discussion:
- external tools like jps and jstack could be kept external (no integration of cmd line calls into server)
- print out queues of executer service
- en-/disable verbose mode

**Comment by szarnekow** [comment]
We could also expose results from querying the JVMs Management Beans (via `java.lang.management.ManagementFactory`, e.g.

- `java.lang.management.MemoryMXBean`
- `java.lang.management.ThreadMXBean`
