### ISSUE TITLE
Validation error in arrow function

### ISSUE THREAD

**Issue by dbo** [eclipse/n4js#181]
##### foo.n4js.xt
```typescript
const foo = r => {
// XPECT noerrors --> "Not a function or method: void."
    console.log("bar")
    (r as Object)
};

```

**Comment by yoosiba** [comment]
removing `r` as it is not important here

notice this works
```typescript
const foo = () =>  {
    console.log(1)
    2
};
```
this too
notice this works
```typescript
const foo = () =>  {
    console.log(1);
    (console.log(2))
};
```
but not this
```typescript
const foo = () =>  {
    (console.log(1))
    (console.log(2))
};
```

**Comment by mor-n4** [comment]
This is not related to arrow functions. Following @yoosiba 's examples:
```javascript
{
	1
	2
};

{
	1;
	(2)
};

{
	// XPECT FIXME noerrors --> "Not a function or method: int."
    (1)
    (2)
};

{
	// XPECT FIXME noerrors --> "Not a function or method: int."
    1
    (2)
};
```

**Comment by mor-n4** [comment]
Actually, the behavior is correct.

For example,
```
1
(2)
```
is parsed as a single call expression in which `1` is the expression that is expected to evaluate to the function to be invoked. So the compile error is correct.

When running the above snippet in node, you get the error `TypeError: 1 is not a function` (at runtime).

Closing this.
