### ISSUE TITLE
The validation about name clash of imported modules does not work in some cases

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1812]
Mind the attached example to reproduce the behaviour.

[ws_test.zip](https://github.com/eclipse/n4js/files/4966276/ws_test.zip)

<img width="766" alt="Bildschirmfoto 2020-07-23 um 15 46 03" src="https://user-images.githubusercontent.com/20560257/88293679-9fea2000-ccfb-11ea-8895-3d63cfe38189.png">

Note that the validation was shown at some point, but later it was not.

**Comment by mor-n4** [comment]
Probably a duplicate of #27 and #556.

**Comment by mmews-n4** [comment]
Cannot be reproduced. / Issue fixed.
