### ISSUE TITLE
Initial build in LSP server shows more errors than the incremental build

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1846]
It seems there is an inconsistency between the initial build and incremental build in the LSP server: after removing an interface from a module and saving, certain errors show up after the initial build completes. Then, when running a clean and initial build (with command "N4JS: Rebuild"), additional errors show up. A comparison with the behavior in Eclipse suggests that the result of the incremental build is correct.

To reproduce:

1. create a yarn workspace with two projects `ProjectA` and `ProjectB`, with the latter having a dependency to the former.
2. add these files to `ProjectA`:
   IDataCollection.n4js
   ```javascript
   export public interface IDataCollection {
       public size() : number;
   }
   ```
   IDataList.n4js
   ```javascript
   import {IDataCollection} from "IDataCollection";
   
   export public interface IDataList extends IDataCollection {
       public get(idx: number): Object;
   }
   ```
   MainA.n4js
   ```javascript
   import {IDataList} from "IDataList";
   
   let l: IDataList;
   l = null;
   ```
3. add this file to `ProjectB`:
   MainB.n4js (same content as MainA.n4js):
   ```javascript
   import {IDataList} from "IDataList";
   
   let l: IDataList;
   l = null;
   ```
4. clean everything, open VSCode in root folder of yarn workspace project, and wait for initial build to complete.
5. open file `IDataCollection.n4js` and comment out the interface. Save and close this file.
   --> 2 errors show up in non-opened file `IDataList.n4js` (but no other errors)
6. this state is stable, i.e. you can open the two main files, edit them, save them and no additional errors will appear.
7. now execute command "N4JS: Rebuild"
   --> an additional error will show up in `MainB.n4js`
8. now open, touch, and save file `MainA.n4js`. Then close this file.
   --> an additional error will show up in this file (only after closing).

Potential cause: maybe the initial build does not update the index for resources with errors. Maybe this applies to both builds but in case of incremental build it does not show up because the old index state is retained for the resource with errors?

**Comment by mor-n4** [comment]
For comparison:

1) when following the above steps in Eclipse, we never get the errors in the "Main*" files (even after a clean and full build).
2) when compiling the projects (after commenting out the interface) with the headless builder, we get the additional error in `MainB.n4js`.

**Comment by mor-n4** [comment]
A test is available on branch `GH-1846`.

**Comment by mor-n4** [comment]
The additional errors showing up in the full build seem related to this rule in `UserDataMapper#createUserData()`:
https://github.com/eclipse/n4js/blob/08af7aecc5d9d5f74cfd7d1ebce9eb0f2591f25a/plugins/org.eclipse.n4js/src/org/eclipse/n4js/resource/UserDataMapper.java#L150-L157
But has been in place for ages. So why aren't those additional errors not showing up in the incremental build nor in Eclipse?
Possibly because the resource for IDataList.n4js is still loaded or is demand-loaded from source?

**Comment by mmews-n4** [comment]
I had the same problem and boiled it down to a slightly smaller example (see attachment below). Just open it and you see two errors. If you open `ModuleB.n4js`, its error will disappear. When closing this module again, the error will re-appear.

[testyarn.zip](https://github.com/eclipse/n4js/files/5188685/testyarn.zip)

**Comment by mor-n4** [comment]
After some unrelated fixes elsewhere, also test `N4jscBasicTest#testBuildDependentFilesIfFileRemoved()` is now affected by this problem and needs to be adjusted once this problem is fixed (search for `TODO GH-1846` in N4jscBasicTest.n4js).

**Comment by mor-n4** [comment]
For reference:

This was caused by the following code:
https://github.com/eclipse/n4js/blob/3f9e7e8bc31758a69a2a2ebb1dc398fc39635a57/plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/xtext/server/build/WorkspaceAwareResourceLocator.java#L38-L47

This code effectively disabled the fall-back behavior of loading a resource from source when no `TModule` information for that resource is contained in the index, which is the case for resources with unresolved proxies.

What made this bug confusing was that everything worked ok if the resource in question was loaded from source before during the same build run for other reasons, for example because it was in the build queue at a lower index.
