### ISSUE TITLE
Issues persisted in the project state can get out of sync and become incorrect

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1860]
I add two tests to reproduce this:
- `IncrementalBuilderFileChangesTest#testFixFileBetweenSessions`
- `IncrementalBuilderFileChangesTest#testBreakFileBetweenSessions`

**Comment by mor-n4** [comment]
This happens not only if files are changed (as covered by above tests) but also when projects are being added/removed between LSP server sessions.
