### ISSUE TITLE
As a developer I want a command to navigate from an N4JS source file to its generated output file

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#1870]
As a developer I want an easy way to navigate from an N4JS source file to the corresponding output file in an LSP client.

It is sufficient to provide the support currently available in Eclipse-based N4JS. Therefore, it is *not* required to:
1. allow navigation without first opening the source file,
2. provide region-based navigation (i.e. for a selected region in the N4JS source code the corresponding region in the output code will be selected).

However, it should be briefly investigated if the above two and similar improvements can be provided without much effort.

**Comment by mmews-n4** [comment]
LSP provides the endpoint `textDocument/implementation` which can be triggered using either the context menu or the keyboard shortcut `CMD+F12`.
