### ISSUE TITLE
Update min version of node.js to 8, npm to 5

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#204]
Due to changes in the transpiler, we need at least node.js 8 and npm 5.
Update min version accordingly and add test.

**Comment by jpilgrim** [comment]
Switched to branch GH-204a since I used the wrong account on GH-204...

**Comment by yoosiba** [comment]
changes merged  https://github.com/eclipse/n4js/commit/eeb9bff63969125d80d8f53dfb007344dc54f691
