### ISSUE TITLE
As a smith I want to update all libs to module types and the Dockerfile used for enfore builds

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#2044]
Aside from many other reasons, an update is necessary to solve a problem with shebangs for node. The problem arises with the shebang {{#!/usr/bin/env node -r esm}} since this has more than a single argument. This can be solved either omitting the argument using node version >=14 or adding another argument {{-S}} for {{env}} which was introduced with linux coreutils version >=8.30 (described here: https://unix.stackexchange.com/a/477651/4781).

ACs
* Update packages.json files of n4js libs (and others) to use {{"type": "module"}}
* Check that shebang works: {{#!/usr/bin/env node}} with n4js-cli and n4jsd-generator
* Update node to version 14
* Update Linux to use coreutils version >= 8.30

Note: It is also possible to patch linux, described here: https://duntuk.com/how-upgrade-coreutils-latest-version-source

**Comment by mor-n4** [comment]
Duplicate of #2291.
