### ISSUE TITLE
As a smith I want to refactor the implementations of IN4JSCore, -Workspace, -Project, and related

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#2073]
Also remove (as far as time permits):
* the library manager.
* NpmBinary, NpmCLI, etc. (maybe use CliTools instead).
* unnecessary configuration, profiles, variables, environment variables in pom.xml files.
* ...

**Comment by mmews-n4** [comment]
Please check also:
* Occurrences of `Platform.isRunning()`
* Convert methods in org.eclipse.n4js.utils.ProjectDescriptionUtils and
* org.eclipse.n4js.utils.ProjectDescriptionUtils.ProjectNameInfo#eclipseProjectName

**Comment by mor-n4** [comment]
**IMPORTANT**: before merging to master, test the performance of the update of the workspace configuration (i.e. how long does it take to re-compute *ALL* `ProjectConfigSnapshot`s and friends in a large real-world project).

(motivation: I have removed some lazy-processing, e.g. lazy parsing of Semver versions and version constraints)
