### ISSUE TITLE
Broken image link in the project's Oomph setup.

### ISSUE THREAD

**Issue by merks** [eclipse/n4js#2086]
This line references an image that no longer exists:

https://github.com/eclipse/n4js/blob/5890a86b83c2e2e5431e9d5cfde98d8da5ba8901/releng/org.eclipse.n4js.targetplatform/N4JS.setup#L21

Please replace it with one that does currently exist, for example:

https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ide/icons/n4_logo_32.png

I notice because the setup archiver build fails:

https://ci.eclipse.org/oomph/job/setup-archiver/lastBuild/console

```
Mirroring https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo.png
FAILED to load https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo.png
  ERROR: org.eclipse.oomph.util.IOExceptionWithCause: File not found: https://raw.githubusercontent.com/eclipse/n4js/master/plugins/org.eclipse.n4js.ui/icons/n4_logo.png 0 0 0
```

**Comment by mor-n4** [comment]
Thanks for letting us know! I'll have a look.

**Comment by mor-n4** [comment]
Should be fixed now. Please let me know if there are any more problems.

Have a nice week!
