### ISSUE TITLE
Fail-fast if proxies are resolved early

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#219]
Consider adding fail-fast assertions to ensure proxy resolution does not take place before types builder has completed, i.e. before `fullyInitialized==true`.

This can be done by adding something like
```
		// step 0: ensure proxy resolution is allowed
		// (this must be checked before calling #performPostProcessing(), because that would trigger initialization if
		// not done already)
		if (!isFullyInitialized()) {
			throw new IllegalStateException(
					"must not resolve proxies before resource is fully initialized (i.e. types builder done)");
		}
```
at the beginning of `N4JSResource#doResolveProxy()`.

Adding the assertion is easy, fixing the problems uncovered by it could take more time ;-)

**Comment by qtran-n4** [comment]
I remember some time ago when @kduske-n4 was working on the transition states of a resource, we had the idea that we have the transition of states of a resource more explicit making it easier to catch inconsistent states.

**Comment by mor-n4** [comment]
After looking into this some more:

A correct rule for this fail-fast check would have to be as follows:
```java
	@Override
	public EObject doResolveProxy(InternalEObject proxy, EObject objectContext) {
		// step 0: ensure proxy resolution is allowed
		// (this must be checked before calling #performPostProcessing(), because that would trigger initialization if
		// not done already)
		final Script script = getScript();
		final boolean isProxyResolutionAllowed = (script != null && !script.eIsProxy() && !isInitializing())
				|| (script != null && script.eIsProxy());
		if (!isProxyResolutionAllowed) {
			throw new IllegalStateException("proxy resolution was triggered in a resource load state that does not allow proxy resolution");
		}
```

This means we can only check that the types builder does not incorrectly trigger proxy resolution. The reason for this liberal rule is that we cannot distinguish between our internal code (which must not trigger proxy resolution before isFullyInitialized) and external client code (which is allowed to trigger proxy resolution as soon as right after parsing).

Since the types builder is a relatively simple and rather stable by now, adding such a fail fast check does not seem worth it.

Instead, I will update the design document with some information and then close this task as fixed.
