### ISSUE TITLE
FQN are supported in type references

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#222]
Currently in type references it is possible to use FQN to refer to non global type without any imports.

Assuming module Mod1.n4js with content
```typescript
export public var A :string = "Mod1.A";
```
in module Mod2.n4js it is possible to refer to `A` with FQN like:
```typescript
let a : Mod1.A;
```

Type references to `A` should be allowed only with import:
```typescript
import {A} from "Mod1"
let a : Mod1.A;
```
or with the namespace import
```typescript
import * as namespace from "Mod1"
let a : namespace.A;
```

Notice that using namespace with name as the module only looks like the original example:
```typescript
import * as namespace from "Mod1"
let a : Mod1.A;
```
but this is actually different in a way that import is required and the type ref is not fqn but namespace access.

**Comment by lbeurerkellner** [comment]
Note that this only seems to be an Issue for TypeRefs:

```
// variable declaration
var a : Module.Class

// formal parameter declaration
function f1(m : Module.Class) {}

// return value declaration
function f2() : Module.Class { return null}

// type variable bound declaration
function <T extends Module.Class>generic() {}

// type argument
<Module.Class> generic();
```
(the IDEs validates all of the snippet as valid N4JS, no additional imports were used)

For identifier references however, this seems to be validated correctly:

```
function f(p : any) {}

var a = new Module.Class(); // Couldn't resolve reference to IdentifiableElement 'Module'
f(new Module.Class()); // Couldn't resolve reference to IdentifiableElement 'Module'
```

**Comment by yoosiba** [comment]
Yes, this is only in type refs.
There is a clash, were between namespace and "FQN". In the end without having a context it is hard to say if `foo.Bar` is a FQN access or namespace access. 
Maybe there was some FQN leftover in the handling of the type refs, that is used now to handle the namespace access. 
If I remember correctly `foo.bar.Baz` won't work - namespace imports can have only 2 "segments" so it won't be resolved correctly.

Anyway, there is issue for type refs only. And yes, the handling in scopes is different.

**Comment by lbeurerkellner** [comment]
I am currently looking into this.
