### ISSUE TITLE
Add intl. parameters to Number.toLocaleString

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#224]
Number.toLocaleString is defined in the ECMAScript spec as follows:

```
Number.prototype.toLocaleString ( [ reserved1 [ , reserved2 ] ] )
```

The parameters are defined in the i18n API (ECMA-402):
https://www.ecma-international.org/ecma-402/4.0/index.html#sup-number.prototype.tolocalestring

```
Number.prototype.toLocaleString ( [ locales [ , options ] ] )
```

For details about these parameters, see https://www.ecma-international.org/ecma-402/4.0/index.html#numberformat-objects

We shoud update our signature of that method to
```
toLocaleString(locales=: string, options=: ~Object with {..})
```

(or add a helper type for the options)

**Comment by yoosiba** [comment]
fixed https://github.com/eclipse/n4js/commit/61bae37c8430c7e8a82cdbb4a5794c6a4e3cb8da
