### ISSUE TITLE
I18l issue with date

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#249]
duplicated definition file for date causes validation / compilation problems. The `Date.n4js` is in both 
 * n4js-runtime-es2015
 * n4js-runtime-ecma402

using only one library causes compilation issues in code, using both causes validation error in the manifest.

Remove `Date.n4js` from `n4js-runtime-es2015`.
Ensure proper visibility of types in `n4js-runtime-ecma402`

**Comment by mor-n4** [comment]
with the original PR, the following code is legal N4JS but breaks at runtime:
```js
import {Collator} from "IntlClasses";

new Collator();
```
