### ISSUE TITLE
As a smith I need to migrate from org.eclipse.xtext.junit4 to org.eclipse.xtext.testing

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#25]
In Xtext, the platform-independent test utils have been moved from org.eclipse.xtext.junit4 to org.eclipse.xtext.testing. The classes in org.eclipse.xtext.junit4 are being deprecated in Xtext 2.11.

For the very most cases, an adaption of the `MANIFEST.MF` plus "organize imports" should do.

This task cannot be started before using Xtext 2.11 (because the new API won't be available before that).

(moved from internal bug tracker, original reporter: @meysholdt)

**Comment by yoosiba** [comment]
isn't this done as part of #18 ?

**Comment by mmews-n4** [comment]
Yes. However, I recommend a final cleanup/check.
