### ISSUE TITLE
Library cannot (re)install library when package version is not aligend with manifest version.

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#288]
NOTE: observed using npm package from private registry. Should be reproducible by finding package with appropriate latest and previous versions in the public registry.

When 'n4js-runtime-html5' is installed without specifying version, then the latest version is installed, e.g`0.3.7-alpha.12e3d034`
```
[17-10-2017 03:23:28] Fetching 'n4js-runtime-html5' package... [package 1 of 1]
+ n4js-runtime-html5@0.3.7-alpha.12e3d034
added 1 package in 2.154s
[17-10-2017 03:23:30] Package 'n4js-runtime-html5' has been successfully fetched.
```

But, the version from `package.json` is not matching `manifest.n4mf` version. In the Manifest version is defined as  `0.3.0`
![lib](https://user-images.githubusercontent.com/944287/31668052-65ab3d0a-b351-11e7-9b56-c87fee51b9e2.png)

This above is already a bug (in the library). It will affect data use in "Export target platform" and "Reinstall npm libraries".

------
Example with the reinstall of npms.

As a consequence the re install will fail, as that process will use versions saved by the library manager:
 1) User installs `n4js-runtime-html5` without specifying version
   1b) library manager fetches latest version (`0.3.7-alpha.12e3d034`) of `n4js-runtime-html5`
   1c) library manager sees it under version  `0.3.0`
 2) User re-installs all libraries
   2b) library manager removes `n4js-runtime-html5`
   2c) library manager tries to install `n4js-runtime-html5@0.3.0`

After 2c) is executed either:
 a) user gets different version of the library than he was using (v0.3.0 not in registry)
 b) library manager shows error that library cannot be fetched (v0.3.0 not in registry)

**Comment by mmews-n4** [comment]
Since the library manager uses npm to install all dependencies, also version requirements are solved by npm. Closing this issue as invalid.
