### ISSUE TITLE
As a smith I need a Data-Flow analyses engine (with warnings if a ref is used before initialization)

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#331]
## Acceptance Criteria
- data effects are collected and saved to every graph node
- xpect method to test that
- xpect tests for every expression that cause data effects

```javascript
function f() {
	let x, y, z;
	
	// XPECT FIXME warning --> "x is not initialized"
	y = x;
	
	if (true) {
		z = 5;
	}
	
	// XPECT FIXME waring --> "x might not be initialized"
	console.log(z);
	
	// XPECT FIXME warning --> "x is not read after this assignment"
	x = 10;
	
	return y;
}
```

**Comment by yoosiba** [comment]
@mmews-n4 close this?

**Comment by mmews-n4** [comment]
The PR #390 included only the first part (preparations, graph improvements, smoke test and other fixes). There will be a second PR for this user story.

**Comment by mmews-n4** [comment]
Guards are done in #464
