### ISSUE TITLE
As a developer I want the headless compiler to show a build identifier

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#345]
The N4JS headless compiler should show an identifier for the build, maybe when given a command line option like `--version` and/or when showing the help.

Important: this identifier should be in sync with the identifier already available in the N4JS IDE! It must be possible to tell if a particular headless compiler and IDE were created during the exact same build.

ACs:
1. headless compiler shows a build identifier.
2. it is possible for a user to easily tell if a headless compiler executable and IDE executable derive from the exact same build.

**Comment by mmews-n4** [comment]
done in #1503
