### ISSUE TITLE
As a smith I want to clean up / refactor code related to JSX / React

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#358]
Some of the code related to the handling of JSX / React needs some refactoring or at least clean up. For example, in many places "React", "react", and "index" are hard-coded and string comparisons are used more than necessary (ideally, `ReactHelper` should be the only class that uses those strings).

A good entry point is class `JSXBackendHelper` and its use inside the transpiler.

AC:
1. make sure no react-related string literals and string comparisons are used by `JSXBackendHelper` and the transpiler (as far as possible),
2. make sure the implicit import created by the transpiler for JSX elements does not introduce name clashes with existing language constructs, i.e. the following code should not produce duplicate variables in the output code and should not crash at runtime:
```javascript
let React = 0;
console.log(<div></div>);
React;
```
3. make sure the use cases documented IDE-2858 are all supported after the refactoring.
4. fix caching of backends in `JSXBackendHelper` (see comment below).

**Comment by yoosiba** [comment]
@mor-n4 so, can we close this?

**Comment by mor-n4** [comment]
No. The merged PR links here only because this is the follow-up.

**Comment by qtran-n4** [comment]
A small fix was done in https://github.com/eclipse/n4js/issues/426. We still need to improve the JSXBackend class.

**Comment by mor-n4** [comment]
The caching of backends in `JSXBackendHelper` seems incorrect because the cache is never cleared (and thus cache clear is effectively the responsibility of whoever injects the `JSXBackendHelper`, failing for example if it is injected into classes that are singletons, because in that case the cache is never cleared).

Probably caching can be removed altogether because now `ReactHelper` is caching the react module.
