### ISSUE TITLE
Inform user when running tests that required n4jsc.jar

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#360]
Currently, many tests in the org.eclipse.n4js.hlc.test such as SingleFileCompileN4jscJarTest.java require that n4jsc.jar exist in the _target_ folder to be able to run locally. However, when we freshly oomph N4JS project, this n4jsc.jar certainly does not exist.

### AC
- The user is informed when executing these tests that she/he has to run `mvn clean verify -DnoTests` on her/his local machine first.

**Comment by yoosiba** [comment]
Note that that is true for whole `org.eclipse.n4js.hlc.tests.jar` and this is explained in the `/org.eclipse.n4js.hlc.tests/src/org/eclipse/n4js/hlc/tests/jar/package-info.java`

**Comment by yoosiba** [comment]
Also note that maven build is regenerating all grammars, models, and etc. so if you do maven build in the folders that are in the workspace, you get lots of changes in the workspace.
