### ISSUE TITLE
As a smith I need to bump Xtext from 2.12 to 2.13

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#370]
As a smith I need to bump Xtext from 2.12 to 2.13.

- update dependencies as required
- apply necessary adaptations to code

## Acceptance Criteria

- N4JS uses Xtext 2.13
- design document updated
- build working

**Comment by yoosiba** [comment]
take a look at #61 when updating

**Comment by yoosiba** [comment]
updated to Oxygen and Xtext 2.13 in #637
