### ISSUE TITLE
As a smith I need to bump Maven to latest version including replacing/bumping Maven plugins

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#371]
As a smith I need to bump Maven to latest version including replacing/bumping Maven plugins. In particular deprecated Maven plugins stemming from "codehaus" need to be replaced with new versions.

- bump pom files to use latest
  - latest Maven version
  - latest Tycho version
  - other Maven plugins should be updated as far as possible (latest versions preferred)

Coordinate that update with our approaches of bringing the N4JS build to Eclipse and into the cloud.

## Acceptance Criteria

- build uses latest Maven and Tycho version
- build does not rely on internal Nexus cache (i.e., all Maven plugins are publicly available and not deprecated)
- spec/design document updated accordingly

**Comment by yoosiba** [comment]
resolved in #881
