### ISSUE TITLE
Fix randomly failing performance tests in enfore internal builds

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#372]
At enfore we have additional, non-public performance tests using non-public test projects. These tests are failing at the moment. These failing tests indicate general problems in N4JS and need to be fixed. If possible, internal tests are to be made public and title of this bug may be adjusted accordingly.

The internal details are described in internal project task IDE-2897.

**Comment by mor-n4** [comment]
The solution of this problem did not lead to any changes in Eclipse n4js code.
