### ISSUE TITLE
Adjust module wrapping to contain output folder value based on the manifest

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#394]
Rising popularity of the JS transpilers (babel, type script) causes new pattern to emerge in npm libraries: they contain both source and compiled output.

Changing module wrapping in the compiler would comply with this pattern. This would also simplify our npm exports of the N4JS projects, where currently we need to move compiled code to the root folder.

`Output` field from manifest is not the only extra segment in the compiled code location.
1. What should we do about `compiler id` that comes from multiple transpilers existing for N4JS?
2. What should we do about `project id` (and version)?

AC:
* adjust module wrapping

1. remove project name from output segments
2. remove compiler id (at least for now, later multiple compilers might bring segment back)
3. attach output folder to the module wrapping (i.e. emitted SystemJS imports)

* adjust `NODE_PATH` in runners and testers
* adjust NPM import/export
* adjust NFAR import/export

**Comment by yoosiba** [comment]
@dbo what is package.json property for storing folder name with compiled code?

**Comment by dbo** [comment]
There's no such property in package.json files, just the `main` property to a script.

Regarding 1) and 2), I suggest there should be an option in the manifest to drop these, if not needed. In most cases I suppose users will simply set manifest's `Output` to a `dist` folder which hosts the transpiled output in the same structure it is in the `src` folder. The main point is that consuming N4JS projects should properly generate import/`System.register` statements including the `<project-npm-id>/<Output>/source-path`.

**Comment by yoosiba** [comment]
@dbo one more question

It is old question that we had open for some time (I have notes from 2014).
Currently compiler strips information about source container.
Should we keep stripping it? Consider project with structure:
```
project/src/A1.n4js
project/src2/A2.n4js
project/tst/A3.n4js
project/tst2/A4.n4js
```

and manifest with content:
```
Output: "dist"
Sources {
    source {"src", "src2"}
    test {"tst", "tst2"}
}
```

now, the `dist` folder contains
```
project/dist/A1.js
project/dist/A2.js
project/dist/A3.js
project/dist/A4.js
```

So, compiler strips all information about source container, both type and name.
This makes all files in the dist folder mashed together.
Wouldn't it be better from plain JS consumer point of view, to keep information about source containers?

![source_info](https://user-images.githubusercontent.com/944287/33566820-840def18-d921-11e7-8175-ac95bde8253d.png)

**Comment by dbo** [comment]
@yoosiba I think this is just fine. Developers commonly scope anyway spending a separate output folder, e.g. for src+test I saw a top-level "tests" package.
Said another way: Developers have all the possibilities to influence the consumer's point of view using a top-level folder. In contrast sometimes this mix is even wanted if you think about generated source code, e.g. a generated class that's statically polyfilled manually.

**Comment by mor-n4** [comment]
I think this is related to the fact that the fully-qualified name of a module (and hence that of exported classes, exported variables, etc.) must be independent of the source container's name and path that contains the module's source file. Someone importing from a type should not have to care about which source container the imported type is located in. And thus there is no need to separate output code by source container within the output folder.

If we had different subfolders in the output folder for each source container (if that is what you had in mind), during look-up (import/require) we would have to search all those folders, because all info we have is the fully-qualified name of the element to be imported, without source container info.

If a separation is actually required, this could be achieved by using subfolders within a source container, which would make them become part of the fully-qualified name. This could even be done with separate source containers:
```
Output: "dist"
Sources {
    source {"src"}
    test {"src-test"}
}
```
And then modules as follows:
```
project/src/app/Module1.n4js
project/src/app/Module2.n4js
project/src-test/tests/TestModule1.n4js
project/src-test/tests/TestModule2.n4js
```
That's the Java / OSGi bundle perspective, at least. Maybe with npm there come some special considerations into play.

**Comment by yoosiba** [comment]
so what is the point of having 
```
Sources {
    source {"src", "src2", "src3", .... ""srcN}
}
```

If we don't really distinguish them, if all compiled ends in the same folder,
and we expect user to do special folders in source container if they need to separate sources...
Then having more than one `source`, `test` or `external` is pointless in the manifest.

**Comment by dbo** [comment]
The only use case I've seen so far is regarding generated classes. As I've elaborated already, specifically in that case we even want to mix the trees: One tree has the generated code (nicely separated from the hand-written code) while the other tree has the hand-written polyfills that exactly need to follow the same package/module.

**Comment by yoosiba** [comment]
In general for generated code one could use subfolder in src. But static plyfills are need this. As you said, polyfill needs to follow package/module. We cannot simplify manifest, without changing StaticPolyfill handling.
I guess we keep multiple source folders, for now...

**Comment by yoosiba** [comment]
P.S. I will use `<project-id>` instead of `<project-npm-id>`. N4JS does not really have `project-npm-id`. There is a validation in place that `project-id` does not contain npm forbidden characters. Also the npm exporter we have will use the same logic. I can't rely on package.json to be there, and I don't want to handle situations in which someone exported N4JS project to npm under different name.

**Comment by mor-n4** [comment]
The point of multiple source folders is to separate sources (for organizational purposes), not necessarily to separate files generated by the transpiler. At least that is the Java/OSGi perspective.
