### ISSUE TITLE
Shortcut for synchronizing text editor and file in project explorer

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#412]
In JDT, we can configure a shortcut for synchronizing a text editor and the corresponding file in the project explorer. This is not possible in N4JS IDE. Investigate why it is not possible and if possible enable it.

**Comment by qtran-n4** [comment]
@kduske-n4 raised this issue.

**Comment by kduske-n4** [comment]
@qtran-n4 In the meantime, I found out that, while the required command "Show in (Project Explorer)" is not in the menu, you can still bind a shortcut to it in the keyboard preferences. So the question is maybe why the menu entry is missing, but the shortcut is not an issue.

**Comment by qtran-n4** [comment]
@kduske-n4 Thanks for the hint! I am looking into this right now.

**Comment by qtran-n4** [comment]
@kduske-n4 It works!
<img width="22" alt="screen shot 2017-12-11 at 13 13 58" src="https://user-images.githubusercontent.com/22659566/33831791-cad2e270-de79-11e7-9bbb-b56d11bddeef.png">

**Comment by qtran-n4** [comment]
Fixed
