### ISSUE TITLE
As a smith I want compiled code for project imports against npms to not include main module

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#419]
For every import statement generated code refers to the concrete file.
Also for project imports, e.g. 
```typescript
import * from "express"
```
will result in the same code generated as for
```typescript
import * from "express/index"
```
(assuming `index` is the main module of `express`)
generated code for that import will be contain reference `"@CJS/express/index"`

Consider making exceptions for the project imports, that is 

1. import statement is a project import, i.e. import declaration refers to the project only
2. project from we import is an ExternalProject backed up by npm (but not shipped code!)

then maybe compiled code could refer only to `"@CJS/express"`.
(This short form should apply only when importing ```from "express"```, but not for the latter import ```from "express/index"```)

**Comment by dbo** [comment]
@mor-n4 This has been fixed recently, right?

**Comment by mor-n4** [comment]
This was done as part of `GH-1280`, `GH-1281`, `GH-1326`.
