### ISSUE TITLE
Cannot assign undefined in a typed destructuring pattern

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#428]
**Code snipped**
```javascript
// XPECT noerrors -->
let [a : int, b : int] = [undefined, 0]; // error here

let c : int = undefined; // works
```

**Error message**
`Variable a cannot hold destructured value at index 0: any is not a subtype of int.`

**Note**
Typing a destructuring pattern is only possible like shown below. It is not supported to use a syntax that Typescript uses: `let [a, b] : Array<int>`.

**Comment by qtran-n4** [comment]
Builds are green (n4js-extended yellow because of randomly failing tests).

**Comment by mor-n4** [comment]
Fixed.
