### ISSUE TITLE
As a developer I want to use a fast, easy and reliable IDE-update process

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#429]
Updating the IDE consumes time, especially since it involves updating all dependencies and workspace projects, and building all of it. The process is a hassle also because the IDE forgets about third party libraries and/or built-in libraries. Moreover, it is unknown to the user, if some dependencies (that do not specify a version) have to be re-installed in case their latest version changed.

**Comment by mor-n4** [comment]
Also consider the older ticket #236.

**Comment by mmews-n4** [comment]
since the so-called "big button" this issue seems to be fixed. also, the management of dependencies was improved significantly during 2018 and #1222.
