### ISSUE TITLE
Inconsistent manifests in third party NPMs causing failure when running code from IDE

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#456]
**How to reproduce**
* Clean install IDE
* Open new Workspace, and Hello-World-Project
* Run it
* Should work
* Go to library manager
* Install 'n4js-node'
* Run it
* Should fail

**Solution**
Add validation of inconsistent manifest files to library manager. If installed npm has errors in manifest, undo npm installation.

**Comment by yoosiba** [comment]
@dbo this was discovered while working with `n4js-node` package published to the (internal) npm.
We need to talk how to address this.

**Comment by kduske-n4** [comment]
What errors does the manifest have? What does 'inconsistent' manifests mean?

**Comment by yoosiba** [comment]
@mmews-n4 is this already covered in #653 (merged #673 or upcoming #703) ?

**Comment by mmews-n4** [comment]
No. Until now, I only fixed package.jsons regarding their `author` and `repository` information in #653b.

**Comment by mmews-n4** [comment]
@kduske-n4 As far as I remember it was because the manifest pointed to a source folder that didn't exist at that location.

**Comment by mmews-n4** [comment]
Fixed in iterations on the Library Manger in the last 10 month: validating externals, switch to package.json, better support for NPMs.
