### ISSUE TITLE
As a developer I want support for the ES 2018 syntax of spread operators in object literals

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#46]
This refers to support in the syntax (in the grammar / parser).
The spread operator is currently supported in argument lists, array literals, etc. but not in object literals.

This is required by the transpiler, for example, in order to use spread operators in the output code.

__Adjust:__
- Grammar,
- AST to add property

### Acceptance Criteria:
- Support spread operator syntax
- Add unsupported feature validation, since full support (i.e. type checking, transpiler, etc.) is not part of this task
- Adjust ES6 test suite blacklist
- Update lang-spec (follow-up not allowed, especially changing list of legal expressions in computed property/member names)

(moved from internal bug tracker, original reporter: @mor-n4)

**Comment by mor-n4** [comment]
cf. https://www.ecma-international.org/ecma-262/9.0/index.html#sec-object-initializer
