### ISSUE TITLE
As a smith I want to add support for definition site variance in constraint solver

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#460]
Currently, the constraint solver is ignoring definition site variance when reducing constraints with generic types. For example, given
```javascript
class B {}
class G<out T> {}
```
the constraint `⟨ G<α> <: G<A> ⟩` is incorrectly reduced to `⟨ α = A⟩`, instead of `⟨ α <: A⟩`.

Full example:
```
class A {}
class B extends A {}
class C extends B {}
class G<out T> {}
class H<T> {}

function <T> foo(p:H<T>):G<T> {
	return null;
}

let a: A;
let b: B;
let c: C;

let hb: H<B>;

// XPECT FIXME noerrors -->
let ga: G<A> = foo(hb);
```

Acceptance Criteria:
* adjust constraint solver accordingly.
* add test (more cases than just the above example).

**Comment by qtran-n4** [comment]
Fixed
