### ISSUE TITLE
As a developer I want full internal(!) support for ES6 import/export (incl. re-export)

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#47]
In particular the following:

* Default export of values
* Export under an alias
* Re-export
* Export independent of declaration

(moved from internal bug tracker, original reporter: @mor-n4)

**Comment by mor-n4** [comment]
Currently, N4JS supports a variant of exports that is not allowed in ES6:
```javascript
export default let x = "some value";
```
Once default export of values is supported, i.e. `export default <expression>`, the above should be disallowed. A validation for doing so was already added but had to be disabled temporarily to not break existing code. Search for `GH-47` in class `ASTStructureValidator`.

**Comment by mor-n4** [comment]
> Currently, N4JS supports a variant of exports that is not allowed in ES6:
>
> [...]

This comment is obsolete, because in the meantime we have added support for default exports of var/let/const in the transpiler.
