### ISSUE TITLE
Improve logging output when N4JSD files cannot be installed due to version mismatches

### ISSUE THREAD

**Issue by kduske-n4** [eclipse/n4js#472]
When the library manager installs an NPM, but cannot find the type definitions in the N4JSD repo due to a version mismatch, it does not print any output to explain the version mismatch.

**Comment by yoosiba** [comment]
npm manager is logging this, but in order to decrease logs in the console, message is not logged in the product.

I will change message log level.

**Comment by yoosiba** [comment]
## installing npm
![log2](https://user-images.githubusercontent.com/944287/35326855-3fd5cc2c-00f8-11e8-91ce-caf47fd52ffa.png)
## reloading npms
![log3](https://user-images.githubusercontent.com/944287/35326894-59aa4ae2-00f8-11e8-943a-b78a353367af.png)

**Comment by kduske-n4** [comment]
Thank you, this looks good!
