### ISSUE TITLE
Remove redundant default initializers from ctor

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#506]
In case a class has a default ctor, but the ctor body sets the same field as well, we should remove redundant default initializer code, e.g.

```typescript
class A {
	constructor(n: number) {
		this.num = n;
	}
	num: number = 5;
}
```
results in a generated ctor:
```typescript
		var A;
		A = function A(n) {
			this.num = 5;
			this.num = n;
		};
```

moved from https://github.com/NumberFour/n4js/issues/33

**Comment by mor-n4** [comment]
After discussion with @dbo we agreed to not do this.

This would require significant analysis, for example to ensure that
1. value of initializer expression is not used in constructor before the value from the ctor's parameter is set.
2. initializer expression does not have a side effect.

Also, this would belong to a kind of output code optimization that we have agreed to postpone, so far.

Closing as WONT FIX.
