### ISSUE TITLE
n4jsc creates workspace folder when invoked

### ISSUE THREAD

**Issue by kduske-n4** [eclipse/n4js#509]
When running the headless compiler, it creates a workspace folder in the current directory. The workspace has the following contents:

```
./workspace/
└── .metadata
    └── .plugins
        ├── org.eclipse.core.resources
        │   ├── .root
        │   └── .safetable
        └── org.eclipse.n4js.external.libraries
            └── .n4npm
                ├── node_modules
                └── package.json
```

It appears however that the node_modules are not used at all during compilation. If we cannot prevent creation of this workspace, we should delete it afterwards (but make sure that it was actually created by the compiler first!).

**Comment by szarnekow** [comment]
This became obsolete with #1535. Closed as fixed.
