### ISSUE TITLE
As a developer I want smaller N4JSC startup time (at least for subsequent runs)

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#513]
Switch of N4JSC to OSGI/Eclipse application introduced longer startup times of the compiler.
Currently it is ~10s and it scales with the size of the compiler. Technical reason for this is Equinox Storage handling of OSGI bundles. In short, N4JSC contains jars with OSGI bundles that Equinox is unpacking into its working location at startup.
Since N4JSC is not using versions (yet?) to avoid different implementations interfere with each other, the location all unpacked bundles exist only temporary on disk, and are deleted at the end of each run.

In this user story we want to decrease at least subsequent startup times. Meaning, if N4JSC in one version (or build from one commit hash) is called multiple times, it should persist unpacked bundles which would make subsequent startup time shorter.

**Comment by yoosiba** [comment]
Startup time is that long partially because compiler is unpacking itself and then it is cleaning up unpacked data. Suppressing cleaning up unpacked data would speed it up significantly. Doing that needs to address some issues:
 * different releases need to use different unpacked data
 * leaving unpacked data on the machine can leave fill up a disk (e.g. Jenskins build nodes that run invoke compiler multiple times.
  * we assume that multiple instances of the same release can run in parallel using the same unpacked data (should that not be true, we would get very unstable builds)

**Comment by yoosiba** [comment]
related  #509 (can be solved in this ticket)

**Comment by szarnekow** [comment]
After finishing #1535, we'll now check how to improve the startup time even futher.

Baseline for a repeated build of OPR without clean on a dev machine:
```
Compile results - Transpiled: 0, Deleted: 0, Errors: 4, Warnings: 16, Duration: 3.716 s
12.52 s
```

In other words, the OPR build without changes is finished in 3.7 seconds whereas the entire process needs 12.5 seconds to finish. 3/4 of the time is not strictly related to the incremental build.

Initially we'll check the cost of classloading and injector creation.

**Comment by szarnekow** [comment]
With the results from branch GH-513 I see numbers in the order of these:
```
Compile results - Transpiled: 0, Deleted: 0, Errors: 4, Warnings: 17, Duration: 2.645 s
5.601 s
```
Out of the total 5.601 seconds, we have a split of `createInjectorAndDoEMFRegistration 1.784 s`, `LanguageServer.initialize 924.0 ms` and the `build 2.645 s`

In a nutshell, the biggest savings were related to unnecessary workspace scanning and duplicate work being done.
About the injector startup: There is not much room for naive speedup with the injector creation due to the heavy pressure on the classloader. Futher progress to be discussed.
