### ISSUE TITLE
Runtime libraries and environments need proper publish config

### ISSUE THREAD

**Issue by dbo** [eclipse/n4js#523]
The `files` section in the `package.json` files still refer to the old structure.

**Comment by yoosiba** [comment]
@dbo I have added `files` section to other npms with generated code, see https://github.com/eclipse/n4js/pull/525/commits/a83726dd4db13d1a0dda0253ece435e3bac5fcca

Shouldn't that be there (at least for consistency) ? Otherwise those are missing in npm, right?

**Comment by dbo** [comment]
As discussed, `files` is a whitelist, this would exclude the other assets which need to be included for publishing.
