### ISSUE TITLE
Validate project manifest in headless compiler

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#561]
Currently, the headless compilers does not validate the manifest files. It should validate them before it starts actually compiling projects.

* Should all manifests be validated, or only those of the projects which the user explicitly requested to be compiled? In other words, should manifests of dependencies also be validated?
* Manifests should be validated before the actual compilation begins, that is, [during project registration with the file based workspace](https://github.com/NumberFour/n4js/blob/master/plugins/eu.numberfour.n4js.generator.headless/src/eu/numberfour/n4js/generator/headless/N4HeadlessCompiler.java#L492).

copied from https://github.com/NumberFour/n4js/issues/337

**Comment by yoosiba** [comment]
more detailed issue #793
