### ISSUE TITLE
Source maps don't work using V8 inspector integration of node.js

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#569]
While N4JS source maps work in the browser with the known limitations (i.e. polyfills), using the new node.js V8 inspector integration with Chrome devtools (`--inspect`, since appr. 6.9) renders debugging to not be possible, no source code is shown at all.

copied from https://github.com/NumberFour/n4js/issues/312

**Comment by mor-n4** [comment]
At the moment, source maps are not a supported feature. Also, we have a user story for this (cf. IDE-2203).

Closing as invalid / duplicate.
