### ISSUE TITLE
Add persisted npm handling log in the Library Manager

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#571]
Managing npm dependencies (i.e. installing) might result in exceptions of various nature (IDE not handling package.json properly, broken npm packages, etc.).
When these things happen natural reaction of the user is to retry their actions, or try to workaround them. As a result bugs reported are often follow up bugs that stand from multiple things done, hiding original action and original bug.

Add persisted external libraries log for better communication. It will help with understanding what were the steps that resulted in the bug, and what were workarounds that resulted in follow up errors.

copied from https://github.com/NumberFour/n4js/issues/306

**Comment by yoosiba** [comment]
@mmews-n4 maybe this does not make sense with #653 and #512 ?

**Comment by mmews-n4** [comment]
Right, this ticket seems obsolete since #653 is all about improving the library manager.
