### ISSUE TITLE
As a user I want a nice Eclipse N4JS website

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#58]
Depends on: Initial Eclipse Commit done.
- change/set hyperlinks to (generated) html pages in the docs project
- change Jenkins job
- other changes as needed
- Manual part of website is already prepared
    - download: see incubation mailing list: add link to N4 release and mark that accordingly
    - generated parts are to be "converted", i.e. Jenkins job adjusted

General idea:
- manually created pages are added to Eclipse website repository
- generated pages (from adoc) are added to gh-pages

(moved from internal bug tracker, original reporter: @mmews-n4)

**Comment by mmews-n4** [comment]
The website can be found here: https://eclipse.org/n4js/
