### ISSUE TITLE
Static polyfill not working with type parameters having recursive upper bounds

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#585]
A (probably) bogus error is showing up when tryping to define a static polyfill for a class that has type parameters with recursive upper bounds.

Filled module:

```ts
@@StaticPolyfillAware

export public class ToBeFilled<T,S extends T> {}
```

Filling module:

```ts
@@StaticPolyfillModule

@StaticPolyfill
export public class ToBeFilled<T,S extends T> extends ToBeFilled<T,S> {} // error: "S is not a subtype of T." at "S"
```

copied from https://github.com/NumberFour/n4js/issues/205

**Comment by mmews-n4** [comment]
maybe related to https://github.com/eclipse/n4js/issues/578

**Comment by mor-n4** [comment]
It's a bug in the scoping.
In the example from the issue description, the second `T` in the last line of the filling module is linked to the first `T` in the filled module, but should be linked to the first `T` in the last line of the filling module.
