### ISSUE TITLE
Disallow extending a class with a non-accessible constructor

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#659]
A.n4js
```javascript
export public class A {
	private constructor() {}
}
```
B.n4js
```javascript
import {A} from "A";

// XPECT FIXME errors --> "Cannot extend class A because its constructor is not accessible." at "A"
class B extends A {}
```

Also look for similar cases (e.g. interfaces?).

**Comment by dbo** [comment]
Why not if the sub class just defines static methods?

**Comment by mor-n4** [comment]
Every class in N4JS has a constructor, at least an implicit one. And that is required to invoke the super class's constructor. But if the super constructor is not accessible, this is impossible.

To disallow instantiation while allowing subclassing, a protected constructor should be sufficient. Don't you think so?

**Comment by dbo** [comment]
No, since it has project visibility.

**Comment by mor-n4** [comment]
Not within the same project, yes. If that is important, you could make the class abstract.

In any case, the inconsistency I mentioned above remains and needs to be fixed. If something is missing we need support for that after the fix.

**Comment by dbo** [comment]
We used to define a private ctor in a common trait/base class to prevent instantiation (like in C++). I think we should allow to define `final abstract` classes to achieve the same effect, although we can't encapsulate this into a trait then.

**Comment by mor-n4** [comment]
Yes, we should think about allowing that. Or we could reconsider the fact that `protected` implies `project` accessibility.
