### ISSUE TITLE
hover/tooltip does not contain JSDoc info for member declarations

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#682]
When hovering over member declarations, the hover does not contain the JSDoc information. It is displayed when hovering over references to these declarations.

Also, it seems as if last character of JSDoc is not recognized in all cases.

**Comment by torstenkraemer** [comment]
Stumbled upon this and I'm missing this feature. Esp. parameter / return descriptions.

**Comment by mmews-n4** [comment]
> Also, it seems as if last character of JSDoc is not recognized in all cases.

I cannot reproduce that.

However, I can see this problem:
<img width="208" alt="Screenshot 2019-06-14 at 16 41 09" src="https://user-images.githubusercontent.com/20560257/59517245-6d98ad00-8ec3-11e9-8a9f-eefae6c247b4.png">
