### ISSUE TITLE
n4jsc ignores resources specified in manifest

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#70]
The manifest allows for specifying resources, that is, folders with arbitrary resources.
When running a project from the IDE, these resource folders are added to the `NODE_PATH` path. The n4jsc does not also behave this way.

For example, see the following manifest:
https://github.com/jpilgrim/mdspex/blob/master/mdspex.tests/manifest.n4mf

and the relevant workaround: https://github.com/jpilgrim/mdspex/blob/master/mdspex.tests/src/org/mdspex/ResourceBasedTest.n4js#L58

### Browser Runner Background
The browser solution depends a lot on the desired technical setup of the web app. In general, 
a reasonable approach would be for a runner to point the web server to resources defined in the project. The web client can load resources through the web server.

(moved from internal issues, original reporter: @jpilgrim)

**Comment by jpilgrim** [comment]
Since we do not use manifest.mf and use npm/yarn install, I assume this issue is not valid anymore.
