### ISSUE TITLE
As a user I want to navigate to test class from test view and quickly open launch config

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#719]
As a user I want to navigate to test class from test view and quickly open launch config so that I can faster run the tests.

In the test view, double clicking a test class should open it. At the moment this is only possible for test cases (i.e. test methods).

Also, since the launch config now may contain important information such as environment variables, it would be nice to easily navigate there via a button in the test view.

**Comment by lbeurerkellner** [comment]
Related: https://github.com/eclipse/n4js/issues/737
