### ISSUE TITLE
Type inference contains error suspected to be caused by proxy

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#72]
The follow code produces an error:

```javascript
export public class C {
	b: B;
	d = new D();
	g() {
		this.b = this.d; // Error: any is not a subtype of B.
	}
}

abstract class B {}

class D extends B {
	protected c: C;
	f() {
		this.c.g(); // removing this line solves the error
	}
}
```

That is, although field `d` of `C` is correctly inferred as `D`, the assignment causes an error. However, this only happens if method `C.g()` is called in `D.f()`, which should be completely independent.

The error is also removed when `C.d` is explicitly typed (e.g. `d: D = new D()`).
No error is shown in the error view.

__Note:__

The following example also demonstrates a way to remove the error by moving the class `D` before class `C`:

```javascript
class D extends B {
	protected c: C;
	f() {
		this.c.g();
	}
}
class C {
	b: B;
	d  = new D();
	g() {
		this.b = this.d; // no error here
	}
}
abstract class B {}
```

### Acceptance Criteria

```javascript
export public class C {
	b: B;
	// at least correctly shown in outline view XPECT typeof d --> D
	d = new D();
	g() {
		// XPECT FIXME noerrors --> "any is not a subtype of B."
		this.b = this.d;
	}
}

abstract class B {}

class D extends B {
	protected c: C;
	f() {
		this.c.g();
	}
}
```

(moved from internal issues, original reporter: @jpilgrim)

**Comment by mor-n4** [comment]
same problem, but using only field initializer expressions (no methods):
```javascript
export public class C {
	b : B;
	d = new D();
	g = (this.b = this.d, ""); // Error: any is not a subtype of B.
}

abstract class B {}

class D extends B {
	protected c: C;
	f = this.c.g; // removing this line solves the error
}
```
