### ISSUE TITLE
Editing a location file removes it from search results in find references

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#724]
To reproduce

1. Create class `A` in `A.n4js`
2. Create class `B` in `B.n4js`, make `B` extend `A`
3. Search for references of `A`
4. Assert when `B.n4js` is in the search results 
5. Edit `B.n4js`, e.g. add/edit a comment and save.
6. `B.n4js` is **removed** from search results 

Expected behaviour (either):
a) search results are updated with correct information (e.g. `B.n4js` is removed if user removes all references, file `C.n4js` is added to the result when user adds reference)
b) search results do not get updated with edits, and user has to re-run search to get new results.

Note that in JDT behaviour `a` is implemented (but does not have this buggy behaviour).

![screencast 2018-04-11 16-36-26](https://user-images.githubusercontent.com/944287/38624225-e29cfa52-3da7-11e8-983c-f28b30448a63.gif)

**Comment by qtran-n4** [comment]
In the class `ReferenceSearchResultContentProvider`, changed resource description is listened and when that happens the tree node in the search result is removed (see method `descriptionsChanged` in this class). We have a problem here: the `ReferenceSearchResultContentProvider` is bound in a private module is not supposed to be overridden via DI.

**Comment by qtran-n4** [comment]
Fixed.
