### ISSUE TITLE
New Test Project Wizard contains incorrect import statement

### ISSUE THREAD

**Issue by bsmith-n4** [eclipse/n4js#74]
### Reproducible Steps

* <kbd>File</kbd> __>__ <kbd>New</kbd> __>__ <kbd>N4JS Project</kbd> (select __Test__ project type from dropdown menu)
* * [x]  `Create test project from greeter file` checkbox enabled
* <kbd>Finish</kbd>

The import statement in the generated test file is as follows:

```javascript
import { Assert } from "n4/mangel/assert/Assert" // Error: Couldn't resolve reference to TExportableElement 'Assert'.

```

Changing this line to the following fixes these errors:

```javascript
import { Assert } from "org/eclipse/n4js/mangelhaft/assert/Assert" // no error
```

**Comment by yoosiba** [comment]
fixed in #142
