### ISSUE TITLE
Code formatter introduces compilation error in generic default parameters

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#762]
Code formatter changes `f1a` to `f1b` which is compilation error in N4JS.
```typescript
function f1a(data : Array<Object> =){}
function f1b(data : Array<Object>=){} //error
```

Note that using square bracket notation is working in both cases
```typescript
function f2a(data : [Object] =){}
function f2b(data : [Object]=){}
```

AC:

- code formatter does not change `> =` to `>=`
- or we make `>=` compilable

**Comment by mmews-n4** [comment]
This is related to #491
