### ISSUE TITLE
Delay when invoking Open Type dialog

### ISSUE THREAD

**Issue by kduske-n4** [eclipse/n4js#765]
In larg(er) projects, the open type dialog has a noticeable delay (1-2s) when it is invoked. Since this dialog is used a lot when navigating a large codebase, the delay interrupts the thought process. If I remember correctly, the delay was introduced in the last two months. In fact, the IDE from March 5th does not have it.

**Comment by lbeurerkellner** [comment]
Can you provide further instructions on how to reproduce this? I just tested this with the current OPR master and did not face any performance issues. Have you had a lot of editors open?

**Comment by kduske-n4** [comment]
The number of open editors does not affect the delay. I don't know why you would not see this issue, but it's not just my machine that's affected. I'm using the build from April 13th. I'll keep an eye on it, but so far I haven't found any factors that influence the delay.

**Comment by kduske-n4** [comment]
After creating a new workspace, the delay is gone. Not sure why this would influence it, and I think it's worth to investigate. I still have the old workspace if you'd like to have a look.

**Comment by kduske-n4** [comment]
This seems to be fine now, it can be closed from my POV @mmews-n4. I haven't seen an instance of this in months.
