### ISSUE TITLE
As a user I want to run/test things from the Yarn workspace folder

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#767]
Instead of running things from a temporarily created folder, I want to run things from the yarn workspace folder and re-use the yarn installed node_module folder.

**Comment by mmews-n4** [comment]
Is this ticket (and related branch) still valid with respect to our efforts on switching to package.json and yarn workspace support?

**Comment by mor-n4** [comment]
This issue is superseded by `#1154` and `#824`. Closing as duplicate.
