### ISSUE TITLE
Incorrect warning about empty intersection type

### ISSUE THREAD

**Issue by mor-n4** [eclipse/n4js#787]
```javascript
class C {
	public field: int;
}

class G<T> {}

// XPECT FIXME nowarnings --> "An intersection type should not contain more than one class. Otherwise there cannot exist a value of such a type."
let gi: G<~r~C> & G<~w~C>;
```

**Comment by jpilgrim** [comment]
The warning is correct, albeit for wrong reasons. I'm currently working on this issue and I will improve the validation (to add warnings for correct reasons).

Here is an example why it won't work:

```
// XPECT warnings --> 
let g9: G<~r~C> & G<~w~C>;
// XPECT errors --> "G<C> is not a subtype of intersection{G<~r~C>,G<~w~C>}."
g9 = new G<C>(); 

// if we would use g9 where only a G<~r~C> is expected, 
// we would be able to add a ~r~C only, which would not work for G<C>
// see below:

class ReadC { public get y() { return null;} };
function f(p: G<~r~C>) { p.set(new ReadC())}
f(g9);   
```

@mor-n4, I do not see any solution for T in T <:  G<\~r\~C> & G<\~w\~C>, do you?

**Comment by mor-n4** [comment]
T has a solution: the type `undefined`:
```
let gi: G<~r~C> & G<~w~C>;

let u: undefined;
gi = u;
```
If T is covariant or contravariant there is also the solution `G<undefined>`:
```
class GO<out T> {}

let go: GO<~r~C> & GO<~w~C>;

let gou: GO<undefined>;

go = gou;
```

Please note that all this is related to the topic of how to deal with "empty intersections" and there is a user story for this (see IDE-2302).

**Comment by jpilgrim** [comment]
Well... you can assign undefined to gi... but this is not really useful, is it? I will have a look at the discussion. Well, from that perspective also G<C> & G<D> has a solution: undefined.

The other case is more interesting... I will have a look at that.

IMHO "undefined" (or null) are not really solutions. We should create warnings in these cases as well.

**Comment by mor-n4** [comment]
A warning won't hurt and is probably useful, but the wording of the warning should not suggest that an intersection type without a trivial subtype (i.e. no subtype other than type `undefined` and the intersection type itself) is illegal in general. Also the statement "there cannot exist a value of such a type" is not correct, strictly speaking.

This is important, because empty intersection types can occur inside the type system as intermediate solutions and are useful there. These empty intersections are only suspicious if they are explicitly written down by the programmer in the source code (and therefore it makes sense to have a warning in these cases).
