### ISSUE TITLE
As a smith I need two Xpect related files in N4JS repository

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#8]
There are two files in NumberFour/n4js which were not added yet to eclipse/n4js since they contain code originally created by Moritz Eysholdt (@meysholdt), author of Xpect.

After analysis of both files, we (Jens and Moritz) came to the following conclusion:

* ScopeXpectMethod: The originally imported file was called AbstractQnAwareScopingTest. This file was renamed and changed quite often and does contain almost no code of the orignal version (name is different, code is different, some "import statements" remained). We agreed to change copyright notice and remove author tag.
* N4JSCommaSeparatedValuesExpectation is a customised version of CommaSeparatedValuesExpectationImpl. In this case, a fair amount of code written by Moritz can be identified. We therefore decided to add that file with a commit message including Moritz' sign-off (Also-by: Moritz Eysholdt \<his mail address>)

## Acceptance Criteria
- [x] Both files are added to the eclipse/n4js repository with appropriate copyright header and sign-off

**Comment by yoosiba** [comment]
fixed with #9 and #13
