### ISSUE TITLE
As a user I need to be able to define n4jsd files for external libraries in my own project

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#819]
As a user I need to be able to define n4jsd files for external libraries in my own project so that I have typing for otherwise untyped projects without the need of adding the n4jsd files to the n4jsd repository.

This means that the n4jsd file needs to shadow any file in an external library with the same fully qualified name. This is not working at the moment.

Related: #714 (ignore js content of external libraries), #818 (dots in file names)

### Acceptance Criteria

- an example must be set up and work (as test). That is, some JavaScript npm without type definitions is to be used in a project, and in the same project an n4jsd file is shadowing a js file of the external library
  - this has to work at compile time
  - this also has to work at runtime (when the n4jsd is to be ignored)

(IDE-3000)

**Comment by mmews-n4** [comment]
This is solved by #821
