### ISSUE TITLE
As a user I need to be able to define projects which sole purpose is to provide type definitions

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#820]
As a user I need to be able to define projects which sole purpose is to provide type definitions for external libraries. These project then may be added to the https://github.com/NumberFour/n4jsd repository.

At the moment, we do not have good way for users (in particular non-NumberFour users) to write their own type definitions, i.e. n4jsd files providing type information for existing NPMs. We need a project (maybe with a special project type) that provides type information similar to the projects found in https://github.com/NumberFour/n4jsd.

We need to figure out how to call the n4jsd project, if we need a special product type (yes: use "external" introduced in #714, called "validation" at the moment) and so on.

## Acceptance Criteria

- [x] a test workspace exists with two projects
    - one project contains only defintion files for some npm library (which has no type definitions!)
    - another project uses the npm library 
- [ ] optionally a wizard exists for creating such a project, maybe integrated with the quickfix which loads libraries from npm

(IDE-2999)

**Comment by yoosiba** [comment]
Note that this is already supported case for `API-IMPL` projects.

**Comment by mmews-n4** [comment]
closing anyway. tests for n4jsd projects exist.
