### ISSUE TITLE
As a user I want type definitions of external projects separated from original project

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#821]
As a user I want type definitions of external projects separated from original project so that we do not modify the node-module folder managed by yarn and not modify the original project at all.

Instead we need a concept of separated projects which are related to the original projects. We should use concepts similar to TypeScript (separated and included, the latter is to be supported by original project)

Sub-tasks:
- [x] [sub1] add property to package.json of npm A to specify which npm B in which version range is defined by A
- [x] [sub2] change structure of all projects in the repo n4jsd so that they are standalone npms
- [x] [sub3] change scoping (in particular project imports) and transpiler (all imports) to support import of type definitions using the new property
- [x] [sub4] change library manager to use a different target location for definition projects (separation of projects)
- [x] [sub5] new project type "definition": only n4jsd files, no output folder, no transpile
- [x] [sub6] add implicit project dependency for implementation projects to type project (for client projects with n4js nature); introduce typeDeps section in package.json and its validations; implement ordering of dependencies to support module shadowing
- [x] [sub7] Discovery: How can npm scopes (e.g. '@n4jsd') be supported? (requirements and proposal)

Note regarding the library manager install routine:
 - assume that dependencies of type definition projects are available and do not need to be installed

Note regarding implicit project dependencies:
- this mechanism applies to all projects including those of external libraries
- in case plain JS projects come with some n4jsd files (as a courtesy of the author), the mechanism would also be required although these projects may not have an n4js nature
- The following way to deal with this is proposed:
 - create new project type "plainjs" which also will be the new default for projects that don't specify an n4js section
 - all n4js files in plainjs projects are treated like js files, i.e. their TModules are empty
 - a warning should be shown for imports on n4js files of plainjs projects

Note regarding (transitive) (dev-) dependencies:
- transitive devDependencies are not installed by npm/yarn
- assume that a client project C depends on an n4js project N which depends on npm P
 - there exist a type definition project Pt of P which is necessary to validate N
 - hence, the workspace (its external projects) only compiles when Pt is installed/available
 - remember that Pt would not be installed in the workspace of C
-> Pt must be a (runtime) dependency of N --- type definition projects must not be devDependencies

Restrictions:
- type definition projects cannot have a name of an already existing project (esp. the one of its implementation project)
- one type definition project can define exactly one implementation project

## Acceptance Criteria
- [ ] new concept created and specified
- [ ] new concept is implemented by library manager or other components affected by that in a minimal was
- [ ] existing type definition projects are converted to new style if required
- [ ] existing N4JS projects do not break

(IDE-2998)

**Comment by kduske-n4** [comment]
Would it not be possible to allow yarn to manage the type definitions as well? If the type definitions for some npm module are themselves wrapped in an npm module, we could just have yarn handle the installation and updating of type definitions for us. But I'm not sure how or if the shadowing would work in that case.

**Comment by yoosiba** [comment]
this should be aligned with `API-IMPL` project concept.
Type definitions are merged into original npm.
APIs are exist as separate project, but IMPL projects need to say in Manifest explicitly which API they implement.

Which ever direction we go, both concepts do the same thing. `TypeDefinitions - npms` should use `API - NPM` mechanisms, which should be adjusted to fit that use case.

**Comment by mmews-n4** [comment]
Regarding @yoosiba comment above:
Also note that branch GH-714b disabled the error NON_EXISTING_PROJECT for external libraries. (see N4JSProjectSetupValidator)
Please change this in this userstory and re-enable the error or remove/replace it completely.
