### ISSUE TITLE
adaptation of external libraries generates broken manifest files

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#839]
Changes to N4MF done in https://github.com/eclipse/n4js/pull/833 are breaking manifest serialisation which in turn breaks adaptation of npm libraries in library manager.
In N4MF serialising-deserializing test roundtrip is broken. 
expected (should be the same after serialising and deserialising)
```
RequiredRuntimeLibraries {
    n4js-runtime-node,
    n4js-runtime-fetch
}
```
actual
```
RequiredRuntimeLibraries {
    n4js-runtime-node,
}
RequiredRuntimeLibraries {
    n4js-runtime-fetch
}
```

**Comment by lbeurerkellner** [comment]
In a workspace in which a broken manifest is put into the .n4npm folder, the IDE runs into a state in which it is unable to create an injector. This results in an overall very broken state in which almost all N4JS-related functionality is unavailable. 

As part of this issue we want to ensure that this case is handled more gracefully in that it does not abort the creation of the N4JS injector.
