### ISSUE TITLE
As a Smith and Developer I need clarification of how JS/X files are treated in N4JS-IDE and maybe reenable JS/X support

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#855]
N4JS-IDE has been going through several phases of approaching plain `JS/X` files. In the beginning they were fully supported (parsed, validated, recompiled), then they were ignored (no compilation, no support in N4JS projects), now they are partially supported (due to NodeJS/X/NPM support). 
This left us in very inconsistent state:
* `JS/X` files are always parsed
* never compiled
* all validations are applied to `JS/X` resources, but some of them actively check type of the resource (and quickly return without doing actual validation)
* some of our tests are testing behavior in `JS/X` files
* some of our tests check `N4JS/X` specific features in the `JS/X` files!!

As a Smith I need clarification of how we want to approach plain `JS/X` resources and align our system implementation with that.
As a Developer I need spec clarification of how IDE treats `JS/X` files, and I want behavior to be aligned.

AT (if `JS/X` is not supported at all)
* don't parse `JS/X` files
* don't build types for `TModule` of the `JS/X` files
* don't emit code for `JS/X` files
* clarify conditions of placing `JS/X` files in N4JS projects
* change all our tests to use only `JS/X` resources!!
* update spec

AT (if `JS/X` is somehow supported at all)
* clarify conditions of placing `JS/X` files in N4JS projects
* clarify behavior of the validations
* change all our tests to reflect both cases ( `JS/X` and `N4JS/X` resources)
* align implementations
* update spec

**Comment by mmews-n4** [comment]
when working on this issue, note all markers in the code like
> // disabled issues until GH-855 is solved
> /* X-PECT warnings ---

**Comment by mor-n4** [comment]
Good summary! :+1:
