### ISSUE TITLE
As a smith I want to remove N4 archive completely

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#865]
N4 archives / nfars are not used in production. New features (e.g. package.json and others) would be adjusted to nfars or vice versa, nfars might have to be adjusted to the new features. Since nfars are not used, it is reasonable to remove them completely from the code base.

**Comment by lbeurerkellner** [comment]
With the switch from `manifest.n4mf` to `package.json` as project description file (#809 and #812), it will no longer be supported to load the project description of an NFAR archive. Corresponding tests will be removed as part of the efforts to switch to `package.json`.

Furthermore, removing NFAR support implies the following points:

* remove `libraryPaths` from the `ProjectDescription` (N4MF.xcore) model and as a consequence also remove corresponding elements from the N4JS project model (e.g. `IN4JSProject#getLibraries()`, `IN4JSProject#getLibraryFolders()`, `IN4JSArchive`, etc.)
