### ISSUE TITLE
As a developer I want to remove shipped code from IDE and headless compiler (HLC)

### ISSUE THREAD

**Issue by qtran-n4** [eclipse/n4js#877]
Current situation: At the moment, `n4js.lang`, `runtime library` and `mangelhaft` are shipped with `N4JS IDE` as well all as `n4jsc.jar` (i.e. shipped code)

Current changes: Currently, we are in the process of publishing `n4js.lang`, `runtime library` and `mangelhaft` to the public npm registry.  The motivation is that later on the IDE and the HLC can pull these via `npm`. 

Next steps: As a next step, we will probably need to remove the shipped code from the IDE and the HLC. The consequences are as follows:

- for the IDE: when the IDE starts, it will pull the shipped code from the public npm registry via `npm install`
- for the HLC: the `n4jsc.jar` (or the npm pendant `n4js-cli`) can only be executed within a project where the shipped code is available. 

Note that this could be a huge change and needs careful discussion. All our Xpect/Junit tests etc. may need to fetch `n4js.lang`, `runtime library` or `mangelhaft` in order to run at all.

BLOCKED by:
- #1282 (for adjusting tests during this task, it must be clear how to deal with runtime environments/libraries first)

**Comment by mor-n4** [comment]
when working on this issue, also consider #1259
Also search code base for string `GH-1259`.
