### ISSUE TITLE
N4JS-Example-Project: Some tests cannot be executed or produce errors

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#93]
In the example project `n4js.example.tasks.tests`:

### Cannot be started as "Test in Node.js"
* AbstractStorageTest

### Results in errors
* StorageMongoDBTest

### Runs fine
* StorageInMemoryTest
* TaskManagerTest

**Comment by mor-n4** [comment]
`AbstractStorageTest`: this cannot be started because it is an abstract base class.

`StorageMongoDBTest`: what errors? Have you installed & started mongo DB?

**Comment by mor-n4** [comment]
Just checked this. The tests fail due to breaking API changes in the NPM package "mongodb" which is required by the example code.

**Comment by mor-n4** [comment]
I had a quick look into this.

There was a host of issues:

1. a new version of NPM package "mongodb" came out, that entails breaking API changes.
2. the logic for the DB serialization in the example code had been incorrectly modified and was thus broken.
3. the .zip files containing the example code were incorrectly created (i.e. the ".project" files were not included in the archive).
4. the corresponding test was set to `@Ignore` and therefore did not report these problems.
5. the corresponding test did not notice if `.project` files were forgotten from the .zip files containing the example code.

Fixes:

1. example is using a version constraint when installing "mongodb" (now using newest version *before* 3.0.0).
2. fixed example code & .zip files.
3. added instructions for creating the .zip files.
4. removed `@Ignore` on test.
5. added assertions to test that will fail in case ".project" files will be forgotten in .zip files in the future.
6. added instructions to test on how to run test locally.
