### ISSUE TITLE
`noModuleWrap` disables validation

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#965]
using `noModuleWrap` in `package.json` disables validation, e.g.
```javascript
        "moduleFilters": {
            "noModuleWrap": [
                "lib/**"
            ]
        }
```
`noModuleWrap` should affect only wrapping

**Comment by lbeurerkellner** [comment]
As discussed the spec says that `noModuleWrap` has the following meaning:

> Files matching this filter are not wrapped into modules **and they are not semantically validated**. Since they are assumed to be wrapped into modules, declarations inside these modules cannot be referenced by n4js code.

Therefore, the observed behaviour is intended.

**Comment by mor-n4** [comment]
Closing as invalid.
