### ISSUE TITLE
Remove manifest.n4mf files from shipped code projects

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#997]
For now, we keep `manifest.n4mf` files for our shipped code projects (e.g. mangelhaft, runtime libraries, etc.) since at the time of the package.json-merge, existing external tooling was not fully compatible with purely `package.json`-based projects.

To my knowledge this has changed in the meantime, but it needs to confirmed by the past maintainers of said tooling (e.g. n4js-mangelhaft-cli). 

As of #969, we do no longer *publish* `manifest.n4mf` files with runtime environment. However, for all other shipped code projects, they are still published.

**Acceptance Criteria**:

* No longer include `manifest.n4mf` files with shipped code projects

**Comment by mmews-n4** [comment]
@mor-n4 you worked on that, right? Maybe we can close this ticket?

**Comment by mor-n4** [comment]
This was FIXED an merged together with #1027. Closing now.
